### ISSUE TITLE
Remove Custom Legislation Documents

### ISSUE THREAD

**Issue by voodoorai2000** [AyuntamientoMadrid/consul#1013]
What
===
Remove partial to display custom legislations documents

How
===
Search for `<%= render 'custom_documents' %>`

Why
===
We can now upload documents from the admin interface and display them in the user facing legislation process https://github.com/consul/consul/pull/2084

Screenshots
===
![duplicate documents](https://user-images.githubusercontent.com/4169/32546939-eaf0c88c-c480-11e7-87c3-6c37a070168d.png)

Warning
===
There are still a couple of Legislation Processes open and using the custom partial to display documents. Wait until at least the 20th of November 2017 to tackle this issue

**Comment by bertocq** [comment]
Closed by https://github.com/AyuntamientoMadrid/consul/pull/1014
