### ISSUE TITLE
Error changing user nick

### ISSUE THREAD

**Issue by ManjiChiba** [AyuntamientoMadrid/consul#1123]
Only for spanish people (Soy un crack. Ya descubro bugs hasta sin proponérmelo. 😅 )

I found a bug on user validation change.
When the user try to change his nick, an error can ocurred if it put and space on the textbox for it
1) Acces to button "My account"
2) Click over button "Change my access data"
https://imgur.com/a/DAz57
3) Over "Save changes"

I check than the error happend when the user put a space between works.
The error show message is "This nick are in use", but really the error is for the space between words.

**Comment by bertocq** [comment]
Gracias @ManjiChiba ! Sin duda uno que se nos había escapado :). Viendo que eres un contribuidor habitual reportando problemas, me gustaría ayudarte a describirlos mejor para que sea más fácil para los desarrolladores solucionarlos:

- Un título descriptivo ayuda a mejorar la gestión del issue cuando esta en un tablón de Projecto (https://github.com/AyuntamientoMadrid/consul/projects/1) y a entender de un vistazo que ocurre... Por ejemplo "Mejorar el error de validación de nombre de usuario"

- Dar toda la información posible sobre cómo reproducir el error. Esto depende mucho del tipo de error pues a veces el sistema operativo y el navegador usado tienen mucho que ver... otras en realidad lo necesario es descripcion paso a paso de como se ha llegado a obtener el error para que sea fácil de reproducir por un desarrollador. En este caso entiendo que un paso a paso podría ser:
   1. Registrarse en consul
   2. Acceder a "Mi cuenta" para editar mis datos
   3. Actualizar mi nombre de usuario introduciendo un espacio
   4. Pulsar en el botón de Guardar
   5. Aparece el error descrito en la siguiente imagen: adjuntar ahi una imagen de captura de pantalla completa (mucho mejor que una parcial)

- Esta quizás es la mas compleja... pero escribir en ingles es una gran ventaja en github, pues no todos los desarrolladores que pueden contribuir en un projecto opensource hablan castellano (y van a poder entender este issue). También es cierto que no todos los ciudadanos dominan el ingles como para poder componer un issue con el :) (para eso podemos estar nosotros si se hace un buen trabajo con los puntos anteriores)

- La última sería (y aplica a otros issues que he visto has creado) Es individualizar.. un issue para cada problema (son gratis!) de forma que puedan atacarse por separado y gestionarse mas fácilmente en el Roadmap. Sinó alguien que este de "gestor" como me toca a mi esta semana tiene que dedicarse a editar el issue que has creado, o a crear nuevos ... pudiendo molestar al autor original pensando que se le esta "copiando" :) 

Bueno 🙏  muchas gracias de nuevo ❤️  por seguir contribuyendo y por tu energia! Espero estos consejos los tomes con el mismo buen rollo e intención que los he intentado escribir 🤗🙌

**Comment by ManjiChiba** [comment]
Sí, por supuesto, no hay problema, tomo nota de todo (lo del inglés va a ser más complicado, no se me da bien).

**Comment by ManjiChiba** [comment]
O si alguien que se le de mejor el inglés que a mi, quiere editarlos y traducirlos...
Doy mi consentimiento.

**Comment by decabeza** [comment]
Este issue ya está resuelto. Los nombres de usuario pueden contener espacios. 😌 

![Screenshot 2019-03-12 at 11 56 10](https://user-images.githubusercontent.com/631897/54195035-f582ab80-44bd-11e9-8cbf-0196cfacef8d.png)

El mensaje de error `ya está en uso` solo aparece en el caso de que realmente ese nombre ya está siendo usado por otro usuario.

![Screenshot 2019-03-12 at 11 58 27](https://user-images.githubusercontent.com/631897/54195286-940f0c80-44be-11e9-88c7-21a5cf170313.png)
