### ISSUE TITLE
Move custom strings from locale files onto /custom folder

### ISSUE THREAD

**Issue by bertocq** [AyuntamientoMadrid/consul#1129]
We should have our /config/locale/* files equal to consul's and any custom string should be moved on to the /config/locale/custom/* structure

After that we'll be able to start translating on to other languages the project with https://crowdin.com/project/decide-madrid/

@ferraniki has shown interests in helping us with Valencian translations for custom Decide Madrid strings 👏

**Comment by aitbw** [comment]
I'm on it

**Comment by bertocq** [comment]
@aitbw I would recommend to tackle this task one file at a time .. maybe not one file per PR but at least an amount that can be easily reviewable :) Or we can end up with a great amount of work done stuck for a week or so and conflicts will start appearing :(

**Comment by aitbw** [comment]
Copy that, @bertocq 👌

**Comment by decabeza** [comment]
Already done on: https://github.com/AyuntamientoMadrid/consul/pull/1273, https://github.com/consul/consul/pull/2469, https://github.com/AyuntamientoMadrid/consul/pull/1397, https://github.com/AyuntamientoMadrid/consul/pull/1406, https://github.com/AyuntamientoMadrid/consul/pull/1411, https://github.com/AyuntamientoMadrid/consul/pull/1499.

Now main `config/locales` files for **en** and **es** have the same content. 😌
