### ISSUE TITLE
Bug in a budget view

### ISSUE THREAD

**Issue by rxnetwalker** [AyuntamientoMadrid/consul#1130]
Bad render at https://decide.madrid.es/presupuestos/presupuestos-participativos-2017/proyecto/662

![error_presupuestos_participativos](https://user-images.githubusercontent.com/9430332/35215459-9aa21f74-ff64-11e7-8fa9-21b44ccb960c.png)

Content out of budget-investment-show section.

**Comment by voodoorai2000** [comment]
Appreciate it @rxnetwalker!
We are working on it!

**Comment by bertocq** [comment]
Hotfix at https://github.com/AyuntamientoMadrid/consul/commit/547229f6c3117733465b9aab95634e6447c22d67 deploying to Preproduction. Thanks @rxnetwalker for the report!

**Comment by bertocq** [comment]
@rxnetwalker fixed! 💯 👏  again for the tip 🤗

**Comment by rxnetwalker** [comment]
Report come from Margarita Padilla, she's already collaborating with us (ParticipaLab) in a research about Decide Madrid focus on participatory budget and many more features and modules of the platform.
