### ISSUE TITLE
Hunt the flaky - Commenting polls Voting comments Update

### ISSUE THREAD

**Issue by voodoorai2000** [AyuntamientoMadrid/consul#1173]
What
===
- Fix flaky spec
`rspec ./spec/features/comments/polls_spec.rb:483 # Commenting polls Voting comments Update`

```
Failures:
  1) Commenting polls Voting comments Update
     Failure/Error: expect(page).to have_content "1"
       expected to find text "1" in "I disagree 0"
     # ./spec/features/comments/polls_spec.rb:495:in `block (5 levels) in <top (required)>'
     # ./spec/features/comments/polls_spec.rb:494:in `block (4 levels) in <top (required)>'
     # ./spec/features/comments/polls_spec.rb:486:in `block (3 levels) in <top (required)>'
```

How
===
- [ ] Explain why the spec was flaky, or under which conditions/scenario it failed randomly
- [ ] Explain why your PR fixes it
- [ ] Backport to Upstream

Tips
===
- Run multiple times a single spec from the command line:
```
for run in {1..3}
do
  rspec ./spec/features/comments/polls_spec.rb:483
done
```

- Running a single spec in Travis:
Add option `:focus` to the spec and push your branch to Github, for example:
`scenario 'Show', :focus do`

- Running specs in the order they failed
After executing rspec you can see the seed used, add it as an option to rspec, for example
`rspec --seed 55638` 

Other things to watch out for
- Random generated values in the code that it’s covering
- Time related issues (current time or two time comparisons)

- More general tips:
https://semaphoreci.com/community/tutorials/how-to-deal-with-and-eliminate-flaky-tests

**Comment by vicentemendozam** [comment]
I'll try this one!

**Comment by bertocq** [comment]
Seems like hunted by #1212 , great work @aitbw 🙌
