### ISSUE TITLE
Hunt the flaky - Emails Users without email should not receive emails

### ISSUE THREAD

**Issue by voodoorai2000** [AyuntamientoMadrid/consul#1176]
What
===
- Fix flaky spec
`rspec ./spec/features/emails_spec.rb:509 # Emails Users without email should not receive emails`

```
Failures:
  1) Emails Users without email should not receive emails
     Failure/Error: expect(page).to have_content 'Have you thought about...?'
       expected to find text "Have you thought about...?" in "Decide Madrid Language: Transparency Open data Local Forums Blog Notifications My activity My account Sign out Debates You are in Proposals Voting Processes Participatory budgeting More information Go back Proposal 2 title Manuela12 • 2018-01-30 • No comments • Proposal code: MAD-2018-01-2 In summary what we want is... 2 Proposal description Additional documentation http://external_documention.es External video https://youtu.be/nhuNb0XtRhQ All city Related content (0) Add related content SUPPORTS 0% / 100% No supports 53,726 supports needed Support SHARE twitter facebook google_plus FOLLOW Follow citizen proposal COMMUNITY Participate in the user community of this proposal. Access the community Comments (0) Notifications (0) Documents (0) Sort by Leave your comment Open government This portal uses the CONSUL application which is open-source software. From Madrid out into the world. For technical assistance enters technical assistance Participation Decide how to shape the Madrid you want to live in. Transparency Find out anything about the Madrid City Council. Open data Every detail about the City Council is yours to access. Ayuntamiento de Madrid, 2018 | Privacy Policy | Terms and conditions of use | Accessibility Twitter Facebook Blog YouTube Instagram"
     # ./spec/support/common_actions.rb:133:in `comment_on'
     # ./spec/features/emails_spec.rb:513:in `block (3 levels) in <top (required)>'
```

How
===
- [x] Explain why the spec was flaky, or under which conditions/scenario it failed randomly
- [x] Explain why your PR fixes it
- [x] Backport to Upstream

Tips
===
- Run multiple times a single spec from the command line:
```
for run in {1..10}
do
  rspec ./spec/features/emails_spec.rb:509
done
```

- Running a single spec in Travis:
Add option `:focus` to the spec and push your branch to Github, for example:
`scenario 'Show', :focus do`

- Running specs in the order they failed
After executing rspec you can see the seed used, add it as an option to rspec, for example
`rspec --seed 55638` 

Other things to watch out for
- Random generated values in the code that it’s covering
- Time related issues (current time or two time comparisons)

- More general tips:
https://semaphoreci.com/community/tutorials/how-to-deal-with-and-eliminate-flaky-tests

**Comment by iagirre** [comment]
I'll do this one.

**Comment by bertocq** [comment]
Okey @iagirre we just need the final step, and that's backporting the fix at #1206 to consul (as I've checked we've that same spec there https://github.com/consul/consul/blob/master/spec/features/emails_spec.rb#L494-L503

And we can close this issue :)

**Comment by bertocq** [comment]
👏 @iagirre , flaky closed! 🌈

**Comment by aitbw** [comment]
Sorry to be a dealbreaker but seems like this one failed again, see [here](https://travis-ci.org/wairbut-m2c-aytomadrid/consul/jobs/339535179)
