### ISSUE TITLE
Hunt the flaky - Commenting debates Voting comments Update

### ISSUE THREAD

**Issue by voodoorai2000** [AyuntamientoMadrid/consul#1177]
What
===
- Fix flaky spec
`rspec ./spec/features/comments/debates_spec.rb:474 # Commenting debates Voting comments Update`

```
Failures:
   1) Commenting debates Voting comments Update
     Failure/Error: expect(page).to have_content "1"
       expected to find text "1" in "I disagree 0"
     # ./spec/features/comments/debates_spec.rb:486:in `block (5 levels) in <top (required)>'
     # ./spec/features/comments/debates_spec.rb:485:in `block (4 levels) in <top (required)>'
     # ./spec/features/comments/debates_spec.rb:477:in `block (3 levels) in <top (required)>'
```

How
===
- [ ] Explain why the spec was flaky, or under which conditions/scenario it failed randomly
- [ ] Explain why your PR fixes it
- [ ] Backport to Upstream

Tips
===
- Run multiple times a single spec from the command line:
```
for run in {1..3}
do
  rspec ./spec/features/comments/debates_spec.rb:474
done
```

- Running a single spec in Travis:
Add option `:focus` to the spec and push your branch to Github, for example:
`scenario 'Show', :focus do`

- Running specs in the order they failed
After executing rspec you can see the seed used, add it as an option to rspec, for example
`rspec --seed 55638` 

Other things to watch out for
- Random generated values in the code that it’s covering
- Time related issues (current time or two time comparisons)

- More general tips:
https://semaphoreci.com/community/tutorials/how-to-deal-with-and-eliminate-flaky-tests

**Comment by aitbw** [comment]
I'm on this one

**Comment by bertocq** [comment]
Seems like hunted by #1212 , great work @aitbw 🙌

**Comment by bertocq** [comment]
Well this one as well gets back to the research queue :( https://travis-ci.org/AyuntamientoMadrid/consul/jobs/338260744

**Comment by voodoorai2000** [comment]
Closed via https://github.com/AyuntamientoMadrid/consul/pull/1241
