### ISSUE TITLE
Hunt the flaky - Commenting legislation questions Turns links into html links

### ISSUE THREAD

**Issue by voodoorai2000** [AyuntamientoMadrid/consul#1180]
What
===
- Fix flaky spec
`rspec ./spec/features/comments/legislation_annotations_spec.rb:139 # Commenting legislation questions Turns links into html links`

```
Failures:
  1) Commenting legislation questions Turns links into html links
     Failure/Error: expect(page).to have_content 'Built with http://rubyonrails.org/'
       expected to find text "Built with http://rubyonrails.org/" in "Manuela582 • Author • 2018-01-30 23:28:26 a comment No votes | I agree 0 I disagree 0 No responses"
     # ./spec/features/comments/legislation_annotations_spec.rb:147:in `block (3 levels) in <top (required)>'
     # ./spec/features/comments/legislation_annotations_spec.rb:146:in `block (2 levels) in <top (required)>'
```

How
===
- [ ] Explain why the spec was flaky, or under which conditions/scenario it failed randomly
- [ ] Explain why your PR fixes it
- [ ] Backport to Upstream

Tips
===
- Run multiple times a single spec from the command line:
```
for run in {1..10}
do
  rspec ./spec/features/comments/legislation_annotations_spec.rb:139
done
```

- Running a single spec in Travis:
Add option `:focus` to the spec and push your branch to Github, for example:
`scenario 'Show', :focus do`

- Running specs in the order they failed
After executing rspec you can see the seed used, add it as an option to rspec, for example
`rspec --seed 55638` 

Other things to watch out for
- Random generated values in the code that it’s covering
- Time related issues (current time or two time comparisons)

- More general tips:
https://semaphoreci.com/community/tutorials/how-to-deal-with-and-eliminate-flaky-tests

**Comment by raul-fuentes** [comment]
I'll do this one

**Comment by bertocq** [comment]
Hey @raul-fuentes you seem to have already tackled https://github.com/AyuntamientoMadrid/consul/issues/1181 🤔

**Comment by bertocq** [comment]
Hey @raul-fuentes you seem to have already tackled https://github.com/AyuntamientoMadrid/consul/issues/1181 :thinking_face:

**Comment by bertocq** [comment]
Great @raul-fuentes 👏  Last step to close this issue! We need a backport to consul of the #1232 fix (I've checked that scenario is present at https://github.com/consul/consul/blob/master/spec/features/comments/legislation_annotations_spec.rb#L139-L152)

**Comment by bertocq** [comment]
Awesome @raul-fuentes another one completed 👏

**Comment by javierm** [comment]
As pointed out in https://github.com/consul/consul/pull/2455#issuecomment-401971618 this sepc still fails sometimes.

**Comment by javierm** [comment]
I forgot to say I started to work on this one a few hours ago.
