### ISSUE TITLE
Hunt the flaky - CSV Exporter Tags Uppercase and lowercase tags work ok together for proposals

### ISSUE THREAD

**Issue by voodoorai2000** [AyuntamientoMadrid/consul#1181]
What
===
- Fix flaky spec
`rspec ./spec/features/api/csv_exporter_spec.rb:428 # CSV Exporter Tags Uppercase and lowercase tags work ok together for proposals`

```
Failures:
  1) CSV Exporter Tags Uppercase and lowercase tags work ok together for proposals
     Failure/Error: expect(csv).to include("health")
       expected ["id", "name", "taggings_count", "kind", "31", "Health", "2", ""] to include "health"
     # ./spec/features/api/csv_exporter_spec.rb:438:in `block (3 levels) in <top (required)>'
```

How
===
- [ ] Explain why the spec was flaky, or under which conditions/scenario it failed randomly
- [ ] Explain why your PR fixes it
- [ ] Backport to Upstream

Tips
===
- Run multiple times a single spec from the command line:
```
for run in {1..10}
do
  rspec ./spec/features/api/csv_exporter_spec.rb:428
done
```

- Running a single spec in Travis:
Add option `:focus` to the spec and push your branch to Github, for example:
`scenario 'Show', :focus do`

- Running specs in the order they failed
After executing rspec you can see the seed used, add it as an option to rspec, for example:
`rspec --seed 55638` 

Other things to watch out for
- Random generated values in the code that it’s covering
- Time related issues (current time or two time comparisons)

- More general tips:
https://semaphoreci.com/community/tutorials/how-to-deal-with-and-eliminate-flaky-tests

**Comment by raul-fuentes** [comment]
I'll handle this

**Comment by bertocq** [comment]
Nice full ✅ build! Lets hope we won't see this flaky again :) 💯 👏 @raul-fuentes !!

Pending Backport PR against consul/consul and we can call this one done :)

**Comment by bertocq** [comment]
sorry no need to backport! this is madrid's only feature and fix :) 🙇 raul!
