### ISSUE TITLE
Fix undefined method `legislation_proposal_path' crash on comment show

### ISSUE THREAD

**Issue by bertocq** [AyuntamientoMadrid/consul#1189]
Rollbar: https://rollbar.com/consul/Participacion/items/1360/?item_page=0&item_count=100&#traceback

```
NoMethodError: undefined method `legislation_proposal_path' for #<#<Class:0x0000000c922e60>:0x00000003599798>
File "/app/helpers/application_helper.rb" line 44 in back_link_to
File "/app/views/comments/show.html.erb" line 3 in _app_views_comments_show_html_erb___2636762736376520828_28115040

ActionView::Template::Error: undefined method `legislation_proposal_path' for #<#<Class:0x0000000c922e60>:0x00000003599798>
File "app/helpers/application_helper.rb" line 44 in back_link_to
File "app/views/comments/show.html.erb" line 3 in _app_views_comments_show_html_erb___2636762736376520828_28115040
```	

As far as I have researched, since the back_link_to refactor we didn't realize any commentable would need to specifiy its own path at /app/helpers/comments_helper.rb#commentable_path

Its very messy to have that knowledge in a helper instead on the models itself as we did for the related content feature

Users are experiencing app crashes at production:
https://decide.madrid.es/comments/149601
https://decide.madrid.es/comments/150089
https://decide.madrid.es/comments/149400
https://decide.madrid.es/comments/149454
https://decide.madrid.es/comments/149586

## Backport
This issue is also present at Consul, a backport PR should be sent after PR & fix is confirmed to be working in production

**Comment by bertocq** [comment]
Possible fix at 263bf1c55f0f922167e08bf0d9b957954f1db79b

**Comment by aitbw** [comment]
Hey @bertocq :wave: what do you need me to do here? :)

**Comment by bertocq** [comment]
Sorry I was trying to clear up roadmaps 🙈 and saw your comment at https://github.com/consul/consul/issues/2364 and directly assigned this to you :( my bad! Fixed it 👍

**Comment by MariaCheca** [comment]
This issue should be closed, the bug has been fixed and the only thing left is the refactor included in the PR https://github.com/consul/consul/pull/2464
