### ISSUE TITLE
Flaky spec: Budget Investments Orders Each user as a different and consistent random budget investment order

### ISSUE THREAD

**Issue by bertocq** [AyuntamientoMadrid/consul#1191]
What
===
Tests that fail randomly are called "flakies", this one seems to be one:

Randomized seed: 18230

Failure:

```
  1) Budget Investments Orders Each user as a different and consistent random budget investment order
     Failure/Error: expect(@first_user_investments_order).not_to eq(@second_user_investments_order)
       expected: value != ["Budget Investment 161 title", "Budget Investment 144 title", "Budget Investment 157 title", "Budget...title", "Budget Investment 162 title", "Budget Investment 145 title", "Budget Investment 158 title"]
            got: ["Budget Investment 161 title", "Budget Investment 144 title", "Budget Investment 157 title", "Budget...title", "Budget Investment 162 title", "Budget Investment 145 title", "Budget Investment 158 title"]
       (compared using ==)
     # ./spec/features/budgets/investments_spec.rb:256:in `block (3 levels) in <top (required)>'
```

How
===
- [ ] Explain why the spec was flaky, or under which conditions/scenario it failed randomly
- [ ] Explain why your PR fixes it
- [ ] Create a backport PR to consul/consul

Tips for flaky hunting
===
- Run multiple times a single spec from the command line:
```
for run in {1..10}
do
  rspec ./spec/features/budgets/investments_spec.rb:256
done
```

- Running a single spec in Travis:
Add option `:focus` to the spec and push your branch to Github, for example:
`scenario 'Show', :focus do`

- Running specs in the order they failed
After executing rspec you can see the seed used, add it as an option to rspec, for example
`rspec --seed 55638` 

Other things to watch out for
- Random generated values in the code that it’s covering
- Time related issues (current time or two time comparisons)

- More general tips:
https://semaphoreci.com/community/tutorials/how-to-deal-with-and-eliminate-flaky-tests

**Comment by raul-fuentes** [comment]
I'll do this one

**Comment by bertocq** [comment]
I'm not creating a new issue for this one (for now ) as I've recalled the flaky this issue mentions and this one:
```
  1) Budget Investments Orders Each user as a different and consistent random budget investment order
     Failure/Error: expect(page).to have_content "You're on page 1"
       expected to find text "You're on page 1" in "Decide Madrid Language: Transparency Open data Local Forums Blog Sign in Register Debates Proposals Voting Processes You are in Participatory budgeting More information Searcher Search Search Go back Participatory budgeting random highest rated Budget Investment 98 title 2018-02-06 • Manuela714 • More hospitals Spend money on this No supports Support Budget Investment 99 title 2018-02-06 • Manuela715 • More hospitals Spend money on this No supports Support Budget Investment 100 title 2018-02-06 • Manuela716 • More hospitals Spend money on this No supports Support Budget Investment 101 title 2018-02-06 • Manuela717 • More hospitals Spend money on this No supports Support Budget Investment 102 title 2018-02-06 • Manuela718 • More hospitals Spend money on this No supports Support Budget Investment 103 title 2018-02-06 • Manuela719 • More hospitals Spend money on this No supports Support Budget Investment 104 title 2018-02-06 • Manuela720 • More hospitals Spend money on this No supports Support Budget Investment 105 title 2018-02-06 • Manuela721 • More hospitals Spend money on this No supports Support Budget Investment 106 title 2018-02-06 • Manuela722 • More hospitals Spend money on this No supports Support Budget Investment 107 title 2018-02-06 • Manuela723 • More hospitals Spend money on this No supports Support First Previous 1 You're on page 2 3 4 Next Last CATEGORIES Open government This portal uses the CONSUL application which is open-source software. From Madrid out into the world. For technical assistance enters technical assistance Participation Decide how to shape the Madrid you want to live in. Transparency Find out anything about the Madrid City Council. Open data Every detail about the City Council is yours to access. Ayuntamiento de Madrid, 2018 | Privacy Policy | Terms and conditions of use | Accessibility Twitter Facebook Blog YouTube Instagram"
     # ./spec/features/budgets/investments_spec.rb:273:in `block (4 levels) in <top (required)>'
     # ./spec/sessions_helper.rb:5:in `in_browser'
     # ./spec/features/budgets/investments_spec.rb:268:in `block (3 levels) in <top (required)>'

```

Are related by the random seed generation. If not I'll create an issue for it

**Comment by bertocq** [comment]
Happened at https://travis-ci.org/AyuntamientoMadrid/consul/jobs/338269295

**Comment by bertocq** [comment]
and at https://travis-ci.org/AyuntamientoMadrid/consul/jobs/338269295

**Comment by bertocq** [comment]
We've only one more thing to close this issue @raul-fuentes , the backport to consul/consul of the spec fix at #1231 (and maybe the investment controller improvement if you think so)

**Comment by bertocq** [comment]
Great @raul-fuentes 👍  issue completed 🎉

**Comment by aitbw** [comment]
I don't like to be bearer of bad news but I think this one isn't entirely mitigated, see [here](https://travis-ci.org/wairbut-m2c-aytomadrid/consul/jobs/339535174)

**Comment by raul-fuentes** [comment]
As you can see in the last point of https://github.com/AyuntamientoMadrid/consul/pull/1231 I am still working on those errors, explicitly referenced here https://github.com/AyuntamientoMadrid/consul/issues/1196 , anyway, thanks because reproduce the flakies is a pain

**Comment by voodoorai2000** [comment]
@raul-fuentes we have made some changes to the random order code for investments[1]

Can you update the seeds used in this test, to be large floats, like the ones returned by calling `rand`? Maybe it helps to fix the flakiness indirectly 😌 

[1] https://github.com/AyuntamientoMadrid/consul/pull/1318

**Comment by raul-fuentes** [comment]
Branches updated, using rand instead of fixed numbers.

Can you confirm me that I have updated the correct branches, please?

**Comment by voodoorai2000** [comment]
Sorry @raul-fuentes where did you make the changes?

**Comment by raul-fuentes** [comment]
[here](https://github.com/wairbut-m2c/consul/tree/backport_1191_flaky_budget_investments_orders_random) and [here](https://github.com/wairbut-m2c-aytomadrid/consul/tree/1191_flaky_spec_budget_investments_orders_random_order) , in the same branches, maybe should I push 2 new ones?

**Comment by raul-fuentes** [comment]
[here](https://github.com/wairbut-m2c/consul/tree/backport_1191_flaky_budget_investments_orders_random) and [here](https://github.com/wairbut-m2c-aytomadrid/consul/tree/1191_flaky_spec_budget_investments_orders_random_order) , in the same branches, maybe should I push 2 new ones?

**Comment by bertocq** [comment]
Seems like this one is hunted!! 👏 🙌

**Comment by javierm** [comment]
It looks like it's failed again: https://travis-ci.org/AyuntamientoMadrid/consul/jobs/469071155
