### ISSUE TITLE
Flaky spec: Commenting Budget::Investments Voting comments Update

### ISSUE THREAD

**Issue by bertocq** [AyuntamientoMadrid/consul#1192]
# What
Tests that fail randomly are called "flakies", this one seems to be one:

**Randomized seed:** 64987

**Failure:**

```
  1) Commenting Budget::Investments Voting comments Update
     Failure/Error: expect(page).to have_content "1"
       expected to find text "1" in "I disagree 0"
     # ./spec/features/comments/budget_investments_spec.rb:481:in `block (5 levels) in <top (required)>'
     # ./spec/features/comments/budget_investments_spec.rb:480:in `block (4 levels) in <top (required)>'
     # ./spec/features/comments/budget_investments_spec.rb:472:in `block (3 levels) in <top (required)>'
```

# How
- [ ] Explain why the test is flaky, or under which conditions/scenario it fails randomly
- [ ] Explain why your PR fixes it
- [ ] Create a backport PR to consul/consul when the fixing PR is approved

### Random values issues
If the problem comes from randomly generated values, running multiple times a single spec could help you reproduce the failure by running at your command line:
```bash
for run in {1..10}
do
  bin/rspec ./spec/features/budgets/investments_spec.rb:256
done
```

You can also try running a single spec in Travis:
Add option `:focus` to the spec and push your branch to Github, for example:
```ruby
scenario 'Show', :focus do
```

But remember to remove that `:focus` changes afterwards when submitting your PR changes!

### Test order issues
Running specs in the order they failed may discover that the problem is that a previous test sets an state in the test environment that makes our flaky fail/pass. Tests should be independent from the rest.

After executing rspec you can see the seed used, add it as an option to rspec, for example:
`bin/rspec --seed 55638` (check **Randomized seed** value at beginning of issue)

### Other things to watch for
- Time related issues (current time, two time or date comparisons with miliseconds/time when its not needed)
- https://semaphoreci.com/community/tutorials/how-to-deal-with-and-eliminate-flaky-tests

**Comment by bertocq** [comment]
Seems like hunted by #1212 , great work @aitbw 🙌

**Comment by bertocq** [comment]
Sorry @aitbw but this one just happened again at master :( I would revisit this one at least (maybe others will be reactivated if the solution is the same for them.. but I'll ping you issue by issue if that happens) https://travis-ci.org/AyuntamientoMadrid/consul/jobs/338096689

**Comment by bertocq** [comment]
Once more :( at stable branch https://travis-ci.org/AyuntamientoMadrid/consul/jobs/338256596

**Comment by bertocq** [comment]
This one is a resilient one! Again :( https://travis-ci.org/AyuntamientoMadrid/consul/jobs/338257532

**Comment by bertocq** [comment]
hope all this occurences really help or give any clues! 🙈  if not I'll stop spaming coments 🙇  https://travis-ci.org/AyuntamientoMadrid/consul/jobs/338260740

**Comment by voodoorai2000** [comment]
Closed via https://github.com/AyuntamientoMadrid/consul/pull/1241
