### ISSUE TITLE
Flaky spec:  undefined method `selected?' at rake db:dev_seed

### ISSUE THREAD

**Issue by bertocq** [AyuntamientoMadrid/consul#1197]
# What
Tests that fail randomly are called "flakies", this one seems to be one:

**Randomized seed:** 6200

**Failure:**

```
  1) rake db:dev_seed seeds the database without errors
     Failure/Error: expect { run_rake_task }.not_to raise_error
       expected no Exception, got #<NoMethodError: undefined method `selected?' for nil:NilClass> with backtrace:
         # ./app/models/budget/ballot/line.rb:31:in `check_selected'
         # ./app/models/budget/ballot.rb:12:in `add_investment'
         # ./db/dev_seeds.rb:540:in `block (2 levels) in <top (required)>'
         # ./db/dev_seeds.rb:537:in `times'
         # ./db/dev_seeds.rb:537:in `block in <top (required)>'
         # ./db/dev_seeds.rb:10:in `section'
         # ./db/dev_seeds.rb:536:in `<top (required)>'
         # ./lib/tasks/db.rake:4:in `block (2 levels) in <top (required)>'
         # ./spec/lib/tasks/dev_seed_spec.rb:12:in `block (2 levels) in <top (required)>'
         # ./spec/lib/tasks/dev_seed_spec.rb:16:in `block (3 levels) in <top (required)>'
         # ./spec/lib/tasks/dev_seed_spec.rb:16:in `block (2 levels) in <top (required)>'
     # ./spec/lib/tasks/dev_seed_spec.rb:16:in `block (2 levels) in <top (required)>'
```

# How
- [ ] Explain why the test is flaky, or under which conditions/scenario it fails randomly
- [ ] Explain why your PR fixes it
- [ ] Create a backport PR to consul/consul when the fixing PR is approved

### Random values issues
If the problem comes from randomly generated values, running multiple times a single spec could help you reproduce the failure by running at your command line:
```bash
for run in {1..10}
do
  bin/rspec ./spec/features/budgets/investments_spec.rb:256
done
```

You can also try running a single spec in Travis:
Add option `:focus` to the spec and push your branch to Github, for example:
```ruby
scenario 'Show', :focus do
```

But remember to remove that `:focus` changes afterwards when submitting your PR changes!

### Test order issues
Running specs in the order they failed may discover that the problem is that a previous test sets an state in the test environment that makes our flaky fail/pass. Tests should be independent from the rest.

After executing rspec you can see the seed used, add it as an option to rspec, for example:
`bin/rspec --seed 55638` (check **Randomized seed** value at beginning of issue)

### Other things to watch for
- Time related issues (current time, two time or date comparisons with miliseconds/time when its not needed)
- https://semaphoreci.com/community/tutorials/how-to-deal-with-and-eliminate-flaky-tests

**Comment by aitbw** [comment]
I think @voodoorai2000 fixed this one [here](https://github.com/AyuntamientoMadrid/consul/commit/868f62cbecd5b73191e4cc2f67c9fe3902dae489#diff-76f98f982e82740450f657f4c0657702)

**Comment by bertocq** [comment]
No @aitbw that was 6 days ago, this issue was created 3 days ago on a build that got that failure. I'll link to a failing travis build with this once I see it again

**Comment by bertocq** [comment]
@aitbw happened again at build https://travis-ci.org/AyuntamientoMadrid/consul/jobs/337784352 with seed 31073

**Comment by aitbw** [comment]
Thanks for the updates, @bertocq. I'm on it.
