### ISSUE TITLE
Fix Proposals menu

### ISSUE THREAD

**Issue by bertocq** [AyuntamientoMadrid/consul#1198]
When you access https://decide.madrid.es/legislation/processes/24/proposals/315-poner-carril-bici-exclusivo-por-todo-madrid you'll see both Proposals & Processes menus being marked as active.

![screen shot 2018-02-03 at 23 56 32](https://user-images.githubusercontent.com/983242/35772390-e1afb89e-093d-11e8-99cb-9ed1ffe38d10.jpg)

We need to avoid more patches and redo the entire menu right, so no new menus or models will break existing ones

This is a great example of **why** all PR's should include an Screenshot unless its really backend-only code

- [ ] Generate at dev seeds content to be able to reproduce visually the problem at localhost
- [ ]  Write an spec assertion to check there is only one element with active class at the menu
- [ ]  Make the code fix

**Comment by aitbw** [comment]
I'm on it

**Comment by bertocq** [comment]
Checked in pre 👍
