### ISSUE TITLE
Flaky spec: Polls Booth & Website Already voted on booth cannot vote on website

### ISSUE THREAD

**Issue by bertocq** [AyuntamientoMadrid/consul#1208]
Warning!
===
This spec probably only fails between 00:00 and 02:00 am Madrid time

# What
Tests that fail randomly are called "flakies", this one seems to be one:

**Randomized seed:** 31908

**Failure:**

```
    1) Polls Booth & Website Already voted on booth cannot vote on website
     Failure/Error: select 'DNI', from: 'residence_document_type'
     Capybara::ElementNotFound:
       Unable to find visible select box "residence_document_type" that is not disabled
     # ./spec/support/common_actions.rb:204:in `officing_verify_residence'
     # ./spec/features/polls/polls_spec.rb:462:in `block (3 levels) in <top (required)>'
```

# How
- [ ] Explain why the test is flaky, or under which conditions/scenario it fails randomly
- [ ] Explain why your PR fixes it
- [ ] Create a backport PR to consul/consul when the fixing PR is approved

### Random values issues
If the problem comes from randomly generated values, running multiple times a single spec could help you reproduce the failure by running at your command line:
```bash
for run in {1..10}
do
  bin/rspec ./spec/features/budgets/investments_spec.rb:256
done
```

You can also try running a single spec in Travis:
Add option `:focus` to the spec and push your branch to Github, for example:
```ruby
scenario 'Show', :focus do
```

But remember to remove that `:focus` changes afterwards when submitting your PR changes!

### Test order issues
Running specs in the order they failed may discover that the problem is that a previous test sets an state in the test environment that makes our flaky fail/pass. Tests should be independent from the rest.

After executing rspec you can see the seed used, add it as an option to rspec, for example:
`bin/rspec --seed 55638` (check **Randomized seed** value at beginning of issue)

### Other things to watch for
- Time related issues (current time, two time or date comparisons with miliseconds/time when its not needed)
- https://semaphoreci.com/community/tutorials/how-to-deal-with-and-eliminate-flaky-tests

**Comment by bertocq** [comment]
Happened again at https://travis-ci.org/AyuntamientoMadrid/consul/jobs/338257526

**Comment by bertocq** [comment]
happened at https://travis-ci.org/AyuntamientoMadrid/consul/jobs/338257548

**Comment by bertocq** [comment]
happened at https://travis-ci.org/AyuntamientoMadrid/consul/jobs/338260710

**Comment by vicentemendozam** [comment]
I'm going for it !

**Comment by iagirre** [comment]
I think that this flaky is related to this one: https://github.com/AyuntamientoMadrid/consul/issues/1195
Maybe I missed something, but, just for clarification: aren't both tests testing the same thing? :thinking:

**Comment by iagirre** [comment]
I'm doing this.

**Comment by decabeza** [comment]
Closed by https://github.com/AyuntamientoMadrid/consul/pull/1342

**Comment by raul-fuentes** [comment]
I'll backport this one
