### ISSUE TITLE
Flaky spec: Admin budget investments Index Filtering by admin

### ISSUE THREAD

**Issue by bertocq** [AyuntamientoMadrid/consul#1217]
# What
Tests that fail randomly are called "flakies", this one seems to be one:

**Randomized seed:** 59860

**Travis failed build:** https://travis-ci.org/AyuntamientoMadrid/consul/jobs/337982693

**Failure:**

```
   2) Admin budget investments Index Filtering by admin
     Failure/Error: expect(page).to have_content('There are 2 investments')
       expected to find text "There are 2 investments" in "Language: Decide Madrid ADMINISTRATION Admin Notifications Delegation My activity My account Sign out Categories Moderated content Polls Participatory budgets Profiles Collaborative Legislation Banners Site customization Moderator activity Configuration settings Newsletters Statistics Manage geozones Signature Sheets iste 378 - Investment projects Advanced filters Filter: All Without assigned admin Without assigned valuator Under valuation Valuation finished Winners Download current selectionThere is 1 investment ID Title Supports Administrator Valuator Scope of operation Feasibility Val. Fin. Selected 3 Realocate visitors 0 Admin 1 No valuators assigned Heading 312 Undecided No"
     # ./spec/features/admin/budget_investments_spec.rb:148:in `block (3 levels) in <top (required)>'
```

# How
- [ ] Explain why the test is flaky, or under which conditions/scenario it fails randomly
- [ ] Explain why your PR fixes it
- [ ] Create a backport PR to consul/consul when the fixing PR is approved

### Random values issues
If the problem comes from randomly generated values, running multiple times a single spec could help you reproduce the failure by running at your command line:
```bash
for run in {1..10}
do
  bin/rspec ./spec/features/budgets/investments_spec.rb:256
done
```

You can also try running a single spec in Travis:
Add option `:focus` to the spec and push your branch to Github, for example:
```ruby
scenario 'Show', :focus do
```

But remember to remove that `:focus` changes afterwards when submitting your PR changes!

### Test order issues
Running specs in the order they failed may discover that the problem is that a previous test sets an state in the test environment that makes our flaky fail/pass. Tests should be independent from the rest.

After executing rspec you can see the seed used, add it as an option to rspec, for example:
`bin/rspec --seed 55638` (check **Randomized seed** value at beginning of issue)

### Other things to watch for
- Time related issues (current time, two time or date comparisons with miliseconds/time when its not needed)
- https://semaphoreci.com/community/tutorials/how-to-deal-with-and-eliminate-flaky-tests

**Comment by bertocq** [comment]
Related with #1218 for sure

**Comment by vicentemendozam** [comment]
I work in this also for related to [https://github.com/AyuntamientoMadrid/consul/issues/1218](url)

**Comment by voodoorai2000** [comment]
Closed via https://github.com/AyuntamientoMadrid/consul/pull/1234
