### ISSUE TITLE
Flaky spec: Legislation Proposals Concerns behaves like notifiable in-app Multiple users

### ISSUE THREAD

**Issue by bertocq** [AyuntamientoMadrid/consul#1219]
# What
Tests that fail randomly are called "flakies", this one seems to be one:

**Randomized seed:** 30261

**Travis failed build:** https://travis-ci.org/AyuntamientoMadrid/consul/jobs/337473103

**Failure:**

```
    1) Legislation Proposals Concerns behaves like notifiable in-app Multiple users commented on my notifiable
     Failure/Error: find(".icon-notification").click
     
     Capybara::ElementNotFound:
       Unable to find visible css ".icon-notification"
     Shared Example Group: "notifiable in-app" called from ./spec/features/legislation/proposals_spec.rb:7
     # ./spec/shared/features/notifiable_in_app.rb:35:in `block (2 levels) in <top (required)>'
```

# How
- [ ] Explain why the test is flaky, or under which conditions/scenario it fails randomly
- [ ] Explain why your PR fixes it
- [ ] Create a backport PR to consul/consul when the fixing PR is approved

### Random values issues
If the problem comes from randomly generated values, running multiple times a single spec could help you reproduce the failure by running at your command line:
```bash
for run in {1..10}
do
  bin/rspec ./spec/features/budgets/investments_spec.rb:256
done
```

You can also try running a single spec in Travis:
Add option `:focus` to the spec and push your branch to Github, for example:
```ruby
scenario 'Show', :focus do
```

But remember to remove that `:focus` changes afterwards when submitting your PR changes!

### Test order issues
Running specs in the order they failed may discover that the problem is that a previous test sets an state in the test environment that makes our flaky fail/pass. Tests should be independent from the rest.

After executing rspec you can see the seed used, add it as an option to rspec, for example:
`bin/rspec --seed 55638` (check **Randomized seed** value at beginning of issue)

### Other things to watch for
- Time related issues (current time, two time or date comparisons with miliseconds/time when its not needed)
- https://semaphoreci.com/community/tutorials/how-to-deal-with-and-eliminate-flaky-tests

**Comment by iagirre** [comment]
I think this PR https://github.com/AyuntamientoMadrid/consul/pull/1294 solves also this issue, because is the same error (in the same line) reported in the issue of the PR.

**Comment by MariaCheca** [comment]
Nice @iagirre! Could you check it to be 100% sure and, in that case, close this issue? 😊

**Comment by iagirre** [comment]
I run this several times and this flaky didn't came up.

**Comment by bertocq** [comment]
Okey closing! Hoping not to see it again :) thanks @iagirre
