### ISSUE TITLE
Flaky spec: Stats graphs custom graphs Unverified users

### ISSUE THREAD

**Issue by bertocq** [AyuntamientoMadrid/consul#1223]
# What
Tests that fail randomly are called "flakies", this one seems to be one:

**Randomized seed:** 26399

**Travis failed build:** https://travis-ci.org/AyuntamientoMadrid/consul/jobs/338096691

**Failure:**

```
    1) Stats graphs custom graphs Unverified users
     Failure/Error: expect(page).to have_content "Unverified users (2)" #including seed admin
       expected to find text "Unverified users (2)" in "Language: Decide Madrid ADMINISTRATION Admin Notifications My activity My account Sign out Categories Moderated content Polls Participatory budgets Profiles Collaborative Legislation Banners Site customization Moderator activity Configuration settings Newsletters Statistics Manage geozones Signature Sheets Stats External stats Polls Participatory Budgets Participatory Budget 2016 Invitations Redeemable codes Direct messages Proposal notifications Incomplete verifications VISITS 1 VOTES IN INVESTMENT PROJECTS 0 INVESTMENT PROJECTS 0 DEBATES 0 PROPOSALS 0 COMMENTS 0 OPEN BUDGETS 0 INVESTMENT PROJECTS 0 PROPOSAL VOTES 0 BUDGETS VOTED 0 INVESTMENT PROJECT VOTES 0 DEBATE VOTES 0 COMMENT VOTES 0 TOTAL VOTES 0 VERIFIED USERS 0 UNVERIFIED USERS 2 TOTAL USERS 2 LEVEL TWO USERS 0 LEVEL THREE USERS 0 VERIFIED USERS WHO DIDN'T VOTES PROPOSALS 0 Participatory budgeting"
     # ./spec/features/admin/stats_spec.rb:378:in `block (4 levels) in <top (required)>'
```

# How
- [ ] Explain why the test is flaky, or under which conditions/scenario it fails randomly
- [ ] Explain why your PR fixes it
- [ ] Create a backport PR to consul/consul when the fixing PR is approved

### Random values issues
If the problem comes from randomly generated values, running multiple times a single spec could help you reproduce the failure by running at your command line:
```bash
for run in {1..10}
do
  bin/rspec ./spec/features/budgets/investments_spec.rb:256
done
```

You can also try running a single spec in Travis:
Add option `:focus` to the spec and push your branch to Github, for example:
```ruby
scenario 'Show', :focus do
```

But remember to remove that `:focus` changes afterwards when submitting your PR changes!

### Test order issues
Running specs in the order they failed may discover that the problem is that a previous test sets an state in the test environment that makes our flaky fail/pass. Tests should be independent from the rest.

After executing rspec you can see the seed used, add it as an option to rspec, for example:
`bin/rspec --seed 55638` (check **Randomized seed** value at beginning of issue)

### Other things to watch for
- Time related issues (current time, two time or date comparisons with miliseconds/time when its not needed)
- https://semaphoreci.com/community/tutorials/how-to-deal-with-and-eliminate-flaky-tests

**Comment by javierm** [comment]
Closing since this spec hasn't failed since we moved from poltergesit to chromedriver in #1387.
