### ISSUE TITLE
Flaky spec: Emails Comment replies Do not send email about comment reply unless set in preferences

### ISSUE THREAD

**Issue by bertocq** [AyuntamientoMadrid/consul#1226]
# What
Tests that fail randomly are called "flakies", this one seems to be one:

**Randomized seed:** 1871

**Travis failed build:** https://travis-ci.org/AyuntamientoMadrid/consul/jobs/338269332

**Failure:**

```
    1) Emails Comment replies Do not send email about comment reply unless set in preferences
     Failure/Error: expect(page).to have_content 'It will be done next week.'
       expected to find text "It will be done next week." in "Decide Madrid Language: Transparency Open data Local Forums Blog Notifications My activity My account Sign out You are in Debates Proposals Voting Processes Participatory budgeting More information Go back Debate 108 title Manuela309 • 2018-02-07 • 1 comment • Debate description Related content (0) Add related content SUPPORTS I agree 0% I disagree 0% No votes SHARE twitter facebook google_plus Comments (1) Sort by Leave your comment Manuela307 • 2018-02-07 01:28:26 Comment body 46 No votes | I agree 0 I disagree 0 No responses | Reply | Leave your reply Open government This portal uses the CONSUL application which is open-source software. From Madrid out into the world. For technical assistance enters technical assistance Participation Decide how to shape the Madrid you want to live in. Transparency Find out anything about the Madrid City Council. Open data Every detail about the City Council is yours to access. Ayuntamiento de Madrid, 2018 | Privacy Policy | Terms and conditions of use | Accessibility Twitter Facebook Blog YouTube Instagram"
     # ./spec/support/common_actions.rb:150:in `reply_to'
     # ./spec/features/emails_spec.rb:207:in `block (3 levels) in <top (required)>'
```

# How
- [ ] Explain why the test is flaky, or under which conditions/scenario it fails randomly
- [ ] Explain why your PR fixes it
- [ ] Create a backport PR to consul/consul when the fixing PR is approved

### Random values issues
If the problem comes from randomly generated values, running multiple times a single spec could help you reproduce the failure by running at your command line:
```bash
for run in {1..10}
do
  bin/rspec ./spec/features/budgets/investments_spec.rb:256
done
```

You can also try running a single spec in Travis:
Add option `:focus` to the spec and push your branch to Github, for example:
```ruby
scenario 'Show', :focus do
```

But remember to remove that `:focus` changes afterwards when submitting your PR changes!

### Test order issues
Running specs in the order they failed may discover that the problem is that a previous test sets an state in the test environment that makes our flaky fail/pass. Tests should be independent from the rest.

After executing rspec you can see the seed used, add it as an option to rspec, for example:
`bin/rspec --seed 55638` (check **Randomized seed** value at beginning of issue)

### Other things to watch for
- Time related issues (current time, two time or date comparisons with miliseconds/time when its not needed)
- https://semaphoreci.com/community/tutorials/how-to-deal-with-and-eliminate-flaky-tests

**Comment by aitbw** [comment]
Whoops, we must have missed this one, fixed in #1286
