### ISSUE TITLE
Flaky spec: Internal valuation comments on Budget::Investments Administrators can create valuation reply as an administrator

### ISSUE THREAD

**Issue by bertocq** [AyuntamientoMadrid/consul#1238]
# What
Tests that fail randomly are called "flakies", this one seems to be one:

**Randomized seed:** 58149

**Travis failed build:** https://travis-ci.org/AyuntamientoMadrid/consul/jobs/339441506

**Failure:**

```
  
  2) Proposals behaves like nested imageable at new_proposal_path Should show successful notice when resource filled correctly and after valid file uploads
     Failure/Error: expect(page).to have_content imageable_success_notice
       expected to find text "Proposal created successfully" in "Decide Madrid Language: Transparency Open data Local Forums Blog Admin Notifications My activity My account Sign out Debates You are in Proposals Voting Processes Participatory budgeting Help Go back Create new proposal How do citizen proposals work? × 1 error prevented this Proposal from being saved. Please check the marked fields to know how to correct them: Proposal title If you are human, ignore this field Proposal summary (maximum 200 characters) Proposal text ◢ Link to external video You may add a link to YouTube or Vimeo Link to additional documentation Descriptive image You can upload one image of following content types: jpeg, jpg, up to 1 MB. Title Remove image Documents You can upload up to a maximum of 3 documents of following content types: pdf, up to 3 MB per file. Add new document Scope of operation Tags Tag this proposal. You can choose from proposed categories or add your own must be accepted I agree to the Privacy Policy and the Terms and conditions of use Recommendations for creating a proposal Do not use capital letters for the proposal title or for whole sentences. On the internet, this is considered shouting. And nobody likes being shouted at. Any proposal or comment suggesting illegal action will be deleted, as well as those intending to sabotage the debate spaces. Anything else is allowed. Enjoy this space and the voices that fill it. It belongs to you too. Open government This portal uses the CONSUL application which is open-source software. From Madrid out into the world. For technical assistance enters technical assistance Participation Decide how to shape the Madrid you want to live in. Transparency Find out anything about the Madrid City Council. Open data Every detail about the City Council is yours to access. Ayuntamiento de Madrid, 2018 | Privacy Policy | Terms and conditions of use | Accessibility Twitter Facebook Blog YouTube Instagram"
     Shared Example Group: "nested imageable" called from ./spec/features/proposals_spec.rb:1464
     # ./spec/shared/features/nested_imageable.rb:166:in `block (3 levels) in <top (required)>'
```

# How
- [ ] Explain why the test is flaky, or under which conditions/scenario it fails randomly
- [ ] Explain why your PR fixes it
- [ ] Create a backport PR to consul/consul when the fixing PR is approved

### Random values issues
If the problem comes from randomly generated values, running multiple times a single spec could help you reproduce the failure by running at your command line:
```bash
for run in {1..10}
do
  bin/rspec ./spec/features/budgets/investments_spec.rb:256
done
```

You can also try running a single spec in Travis:
Add option `:focus` to the spec and push your branch to Github, for example:
```ruby
scenario 'Show', :focus do
```

But remember to remove that `:focus` changes afterwards when submitting your PR changes!

### Test order issues
Running specs in the order they failed may discover that the problem is that a previous test sets an state in the test environment that makes our flaky fail/pass. Tests should be independent from the rest.

After executing rspec you can see the seed used, add it as an option to rspec, for example:
`bin/rspec --seed 55638` (check **Randomized seed** value at beginning of issue)

### Other things to watch for
- Time related issues (current time, two time or date comparisons with miliseconds/time when its not needed)
- https://semaphoreci.com/community/tutorials/how-to-deal-with-and-eliminate-flaky-tests

**Comment by javierm** [comment]
Closing since this spec has changed since it las failed and it hasn't failed since we moved from poltergesit to chromedriver in #1387.
