### ISSUE TITLE
Social share buttons are broken

### ISSUE THREAD

**Issue by bertocq** [AyuntamientoMadrid/consul#1245]
Social share buttons for Twitter, Facebook and Whatsapp are not working properly in production. It could be related with the metatags.

======

Clicking on a share button for facebook just doesn't work (opens a popup that closes itself)

It just may be the gem https://github.com/huacnlee/social-share-button/issues/149 but reverting to previous v0.10 version doesn't fix the problem ... so it may be Facebook side problem 🤔 

Also the debugger validator indicates we need some changes on metadata for facebook
https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fdecide.madrid.es%2Fpresupuestos%2Fpresupuestos-participativos-2018%2Fproyecto%2F9693

![screen shot 2018-02-09 at 21 21 37](https://user-images.githubusercontent.com/983242/36048368-472f71d2-0ddf-11e8-9950-2d488026cc9f.jpg)

**Comment by bertocq** [comment]
Might be related with refactor https://github.com/consul/consul/pull/2463 but fix is not there, additional research is needed

**Comment by voodoorai2000** [comment]
Closed via https://github.com/AyuntamientoMadrid/consul/pull/1325
