### ISSUE TITLE
Flaky spec: Commenting debates Errors on create

### ISSUE THREAD

**Issue by bertocq** [AyuntamientoMadrid/consul#1252]
# What
Tests that fail randomly are called "flakies", this one seems to be one:

**Randomized seed:** 31742

**Travis failed build:** https://travis-ci.org/AyuntamientoMadrid/consul/jobs/340279775

**Failure:**

```
    1) Commenting debates Errors on create
     Failure/Error: expect(page).to have_content "Can't be blank"
       expected to find text "Can't be blank" in "Decide Madrid Language: Transparency Open data Local Forums Blog Notifications My activity My account Sign out You are in Debates Proposals Voting Processes Participatory budgeting Help Go back Debate 5 title Manuela15 • 2018-02-12 • No comments • Debate description Related content (0) Add related content SUPPORTS I agree 0% I disagree 0% No votes SHARE twitter facebook google_plus Comments (0) Sort by Leave your comment Open government This portal uses the CONSUL application which is open-source software. From Madrid out into the world. For technical assistance enters technical assistance Participation Decide how to shape the Madrid you want to live in. Transparency Find out anything about the Madrid City Council. Open data Every detail about the City Council is yours to access. Ayuntamiento de Madrid, 2018 | Privacy Policy | Terms and conditions of use | Accessibility Twitter Facebook Blog YouTube Instagram"
     # ./spec/features/comments/debates_spec.rb:189:in `block (2 levels) in <top (required)>'
```

# How
- [ ] Explain why the test is flaky, or under which conditions/scenario it fails randomly
- [ ] Explain why your PR fixes it
- [ ] Create a backport PR to consul/consul when the fixing PR is approved

### Random values issues
If the problem comes from randomly generated values, running multiple times a single spec could help you reproduce the failure by running at your command line:
```bash
for run in {1..10}
do
  bin/rspec ./spec/features/budgets/investments_spec.rb:256
done
```

You can also try running a single spec in Travis:
Add option `:focus` to the spec and push your branch to Github, for example:
```ruby
scenario 'Show', :focus do
```

But remember to remove that `:focus` changes afterwards when submitting your PR changes!

### Test order issues
Running specs in the order they failed may discover that the problem is that a previous test sets an state in the test environment that makes our flaky fail/pass. Tests should be independent from the rest.

After executing rspec you can see the seed used, add it as an option to rspec, for example:
`bin/rspec --seed 55638` (check **Randomized seed** value at beginning of issue)

### Other things to watch for
- Time related issues (current time, two time or date comparisons with miliseconds/time when its not needed)
- https://semaphoreci.com/community/tutorials/how-to-deal-with-and-eliminate-flaky-tests

### Final thoughts
The true objective of this issue is not "to fix" a flaky spec, but to change a spec that randomly fails into one that we can trust when it passes (or fails). 

That means you've to think "What are we testing here?" and "Can we test the same thing in another way?" or "Are we already testing this somewhere else at least partially?".

Sometimes the fix is to re-write the entire tests with a different approach, or to extend an existing spec. Tests are sometimes written without taking a look at other tests files neither near scenarios.

**Comment by iagirre** [comment]
I'll do this.

**Comment by raul-fuentes** [comment]
I'll do this one

**Comment by javierm** [comment]
Closing since this spec hasn't failed since we moved from poltergesit to chromedriver in #1387.
