### ISSUE TITLE
Flaky spec: Admin spending proposals Index Filtering by geozone

### ISSUE THREAD

**Issue by bertocq** [AyuntamientoMadrid/consul#1255]
# What
Tests that fail randomly are called "flakies", this one seems to be one:

**Randomized seed:** 22482

**Travis failed build:** https://travis-ci.org/AyuntamientoMadrid/consul/jobs/340294258

**Failure:**

```
    1) Admin spending proposals Index Filtering by geozone
     Failure/Error: expect(page).to have_link("Realocate visitors")
       expected to find visible link "Realocate visitors" but there were no matches
     # ./spec/features/admin/spending_proposals_spec.rb:87:in `block (3 levels) in <top (required)>'
```

# How
- [ ] Explain why the test is flaky, or under which conditions/scenario it fails randomly
- [ ] Explain why your PR fixes it
- [ ] Create a backport PR to consul/consul when the fixing PR is approved

### Random values issues
If the problem comes from randomly generated values, running multiple times a single spec could help you reproduce the failure by running at your command line:
```bash
for run in {1..10}
do
  bin/rspec ./spec/features/budgets/investments_spec.rb:256
done
```

You can also try running a single spec in Travis:
Add option `:focus` to the spec and push your branch to Github, for example:
```ruby
scenario 'Show', :focus do
```

But remember to remove that `:focus` changes afterwards when submitting your PR changes!

### Test order issues
Running specs in the order they failed may discover that the problem is that a previous test sets an state in the test environment that makes our flaky fail/pass. Tests should be independent from the rest.

After executing rspec you can see the seed used, add it as an option to rspec, for example:
`bin/rspec --seed 55638` (check **Randomized seed** value at beginning of issue)

### Other things to watch for
- Time related issues (current time, two time or date comparisons with miliseconds/time when its not needed)
- https://semaphoreci.com/community/tutorials/how-to-deal-with-and-eliminate-flaky-tests

### Final thoughts
The true objective of this issue is not "to fix" a flaky spec, but to change a spec that randomly fails into one that we can trust when it passes (or fails). 

That means you've to think "What are we testing here?" and "Can we test the same thing in another way?" or "Are we already testing this somewhere else at least partially?".

Sometimes the fix is to re-write the entire tests with a different approach, or to extend an existing spec. Tests are sometimes written without taking a look at other tests files neither near scenarios.

**Comment by iagirre** [comment]
I tried to run this flaky on my computer, but it's supposed to be pending because spending proposals are not been used at Madrid:
![no-flaky](https://user-images.githubusercontent.com/31625251/36731113-fb395b96-1bc9-11e8-9ef2-2cd798ed6fcb.png)
I looked for this file in consul and it doesn't exists, so... I think the flaky has disappeared (if I didn't miss anything).

**Comment by bertocq** [comment]
You're right @iagirre! [We skipped the whole file](https://github.com/AyuntamientoMadrid/consul/blob/master/spec/features/admin/spending_proposals_spec.rb#L6) because SpendingProposals is no longer in use at Madrid (although we've a huge pending task to completely migrate SpendingProposals to Budget::Investments at madrid and also at Consul)

This issue is no longer valid :) Nice way to hunt a flaky 😊  👏

**Comment by iagirre** [comment]
Shall we help with this migration of SpendingProposals to Budget::Investments?

**Comment by bertocq** [comment]
Its a huge task that has low priority compared with the Flaky Spec issues that keep bloating the travis builds. Also there is still some research to be done of what data should be migrated and how... but thanks Itziar :)
