### ISSUE TITLE
Can Upload podcast of proyects

### ISSUE THREAD

**Issue by ManjiChiba** [AyuntamientoMadrid/consul#1267]
I think maybe a good idea, a new option for can upload a podcast/mp3 file to expose the proyects (always is better than read, and it will be util for blind people).
![uploadoptions](https://user-images.githubusercontent.com/16508522/36254165-493163d6-124a-11e8-83d5-6e490a11714c.png)

**Comment by decabeza** [comment]
Currently users can link external videos on YouTube or Vimeo. Moreover, the most of blind people use a screen reader to hear the screen text and a .mp3 file doesn't seems necessary.
