### ISSUE TITLE
ActionController::InvalidAuthenticityToken: ActionController::InvalidAuthenticityToken

### ISSUE THREAD

**Issue by bertocq** [AyuntamientoMadrid/consul#1298]
https://rollbar.com/consul/Participacion/items/1215/?item_page=0&item_count=100&#instances

We've a lot of `ActionController::InvalidAuthenticityToken: ActionController::InvalidAuthenticityToken` crashes and occurrences have no clear pattern that a quick read can find

This needs some research, starting by checking @vicentemendozam solution for the same problem at agendas repo: https://github.com/AyuntamientoMadrid/agendas/pull/333/files

**Comment by raul-fuentes** [comment]
I'll do this one
