### ISSUE TITLE
Volcado ficheros de PRO a PRE

### ISSUE THREAD

**Issue by bertocq** [AyuntamientoMadrid/consul#1308]
Actualmente se hace un volcado de la bbdd de PRO al servidor de PRE todos los lunes para resetear el entorno y tener datos de prueba válidos. 

Los ficheros (imagenes, documentos, etc...) no estan siendo volcados, y muchos elementos fallan en el servidor de PRE al tener referencias a esos ficheros que fueron subidos en PRO

Es necesario pues:

- [x] Identificar a quien/quienes debemos dirigir la petición
- [x] Realizar la petición 
- [ ] Hacer un seguimiento de la misma hasta que se complete.

Esta tarea puede realizarla cualquiera del core, pero sería ideal que Rai nos transmitiese el know-how que ha acumulado de sus interacciones con el IAM para que no sea siempre el "fallback" de estas tareas

**Comment by voodoorai2000** [comment]
IAM informado, esperando confirmación.
