### ISSUE TITLE
Arreglar orden aleatorio de investments

### ISSUE THREAD

**Issue by bertocq** [AyuntamientoMadrid/consul#1313]
El orden aleatorio de investments falla: desordena las que se muestran, pero en cada página se ven siempre la mismas y las está ordenando por fechas https://decide.madrid.es/presupuestos/3/proyecto?heading_id=49&random_seed=-60472.0 Si me meto en este distrito primero veo las del 24 de enero y en la última página las del 25 de febrero

Esto intento arreglarse con https://github.com/AyuntamientoMadrid/consul/pull/1231 pero seguramente no sea lo correcto, viendo que tenemos una implementación alternativa que usa `setseed` https://github.com/AyuntamientoMadrid/consul/blob/master/app/controllers/human_rights_controller.rb#L86

Itziar intentó esta nueva implementación sin setseed para Budget Investments hace tiempo ... pero realmente el problema que tenemos es de testing, no hay una cobertura lo suficientemente exhaustiva y que busquelos corner case scenarios como para garantizar que no salgan estos problemas en producción

**Comment by voodoorai2000** [comment]
Closed via https://github.com/AyuntamientoMadrid/consul/pull/1318
