### ISSUE TITLE
Propuestas de Inversión de Asociaciones

### ISSUE THREAD

**Issue by voodoorai2000** [AyuntamientoMadrid/consul#133]
Algunas propuestas de inversión han sido deliberadas y acordadas en espacios físicos de debate.

Estas propuestas deberían salir resaltadas con una chapa de Asociación y se debería poder filtrar para que sólo salgan estas.

**Comment by decabeza** [comment]
Cada propuesta llevará una chapa y en el sidebar se podrán ver filtradas las del distrito que estés viendo:

![espacio distrital sidebar](https://cloud.githubusercontent.com/assets/631897/14279905/e81fb09e-fb2f-11e5-999b-24dee4ca216c.png)

En la página principal un enlace a todas las propuestas de espacios físicos:

![screen shot 2016-04-05 at 12 31 39](https://cloud.githubusercontent.com/assets/631897/14279940/0f9d4488-fb30-11e5-8229-4ce0cc4877ac.png)

**Comment by voodoorai2000** [comment]
Closed via #135
