### ISSUE TITLE
Budget results button

### ISSUE THREAD

**Issue by decabeza** [AyuntamientoMadrid/consul#1356]
Background
==

In Admin panel `/admin/budgets/N/budget_investments` appears the button "See results". 

![screen shot 2018-05-09 at 16 05 44](https://user-images.githubusercontent.com/631897/39819147-fb59561a-53a2-11e8-9016-914fadba868b.png)

What we need
==

- Don't show "See results" button on admin page if the winner investments for the current budget weren't calculated.

- Don't allow select "Results phase" if the winner investments for the current budget weren't calculated.

Screenshot
==
**Maybe a disabled option with aclaratory message on `/budgets/N/edit`**

<img width="549" alt="screen shot 2018-03-12 at 17 24 06" src="https://user-images.githubusercontent.com/631897/37296098-385d50a4-261a-11e8-86b5-6d7bd82221f0.png">

**Comment by danielberryman** [comment]
Hi. I'm Daniel. Not sure if admin rules a newbie out but may I have a go at this?

**Comment by voodoorai2000** [comment]
Hey @danielberryman

Thank you so much 😌
Of course, go for it 👍
