### ISSUE TITLE
Fix Budget Heading name edit

### ISSUE THREAD

**Issue by bertocq** [AyuntamientoMadrid/consul#1377]
Somehow in our way to [fix the Budget Group name edit](https://github.com/AyuntamientoMadrid/consul/pull/1361), the Heading name edit has been broken (the @heading variable is not loaded properly, maybe because of the use of slugs instead of ids)

https://rollbar.com/consul/Participacion/items/1452/

Since this is not in use at madrid right now, and we're delayed in the Max heading support issue. We'll fix this one later on

**Comment by bertocq** [comment]
After some research by @voodoorai2000 we've got some tips for the fix:

> Al cambiar la primera vez el nombre de la Partida, no se actualiza el slug
Y la segunda vez que intentas cambiar el nombre, no encuentra la Partida por slug, porque busca por el que debería haberse cambiado antes

> Por ejemplo:
> Primera vez: cambio `Latina` por `Latinas`, todo funciona
Segunda vez: cambio `Latinas`  por `Latinasr` pero al no encontrar el slug `Latinas` no encuentra el heading

**Comment by aitbw** [comment]
Can I go with this one or should I wait for @iagirre to finish with #1384?

**Comment by raul-fuentes** [comment]
I'll do this one

**Comment by raul-fuentes** [comment]
I'll do this one
