### ISSUE TITLE
Prevent multiple clicks on follow proposal

### ISSUE THREAD

**Issue by decabeza** [AyuntamientoMadrid/consul#1378]
Background
==

On proposals show, there is a button to "follow" the proposal. If the user clicks this button the proposal appears on `/users/N?filter=follows&page=1`

How to reproduce the bug
==

1. Go to any proposal show view. Clic repeatedly on "Follow citizen proposal" button.
2. Visit "My activity > Following".
3. The following proposal appears to repeat sometimes.
4. On the proposal show again, click on "Following" (to unfollow), and the button doesn't change.

It's necessary some page refresh for this working again.

Screenshots
==
![screen shot 2018-03-20 at 12 39 38](https://user-images.githubusercontent.com/631897/37652435-ceaf709c-2c3b-11e8-9bf8-f03e1870cdb3.png)

![screen shot 2018-03-20 at 12 34 59](https://user-images.githubusercontent.com/631897/37652432-ce6f26fe-2c3b-11e8-9167-df6657116c92.png)

![screen shot 2018-03-20 at 12 35 23](https://user-images.githubusercontent.com/631897/37652434-ce905f0e-2c3b-11e8-9288-9780a9f216dc.png)

**Comment by iagirre** [comment]
I'll look at this.
