### ISSUE TITLE
Apoyos de espacios distritales

### ISSUE THREAD

**Issue by voodoorai2000** [AyuntamientoMadrid/consul#138]
Para delegar en espacios distritales con criterio, queremos ver que ha apoyado cada espacio distrital.

**Comment by decabeza** [comment]
Añadimos un poco de información en `/delegacion`:

![delegacion_3](https://cloud.githubusercontent.com/assets/631897/14290229/822d5316-fb5e-11e5-87eb-a05f65f8006e.png)

Y creamos una página con las propuestas apoyadas (por ámbito de ciudad y distrito) de cada espacio distrital (como ejemplo):

![delegacion_4](https://cloud.githubusercontent.com/assets/631897/14290258/9f0a7572-fb5e-11e5-836b-6f89ce23ba73.png)

**Comment by voodoorai2000** [comment]
Closed via #https://github.com/AyuntamientoMadrid/consul/pull/143
