### ISSUE TITLE
Add max heading number in Budget Group list

### ISSUE THREAD

**Issue by bertocq** [AyuntamientoMadrid/consul#1384]
At https://github.com/AyuntamientoMadrid/consul/pull/1382 we missed the detail to show to the admin the current Max number of headings users can vote/support at the Budget Groups list:

![screen shot 2018-03-22 at 21 45 12](https://user-images.githubusercontent.com/983242/37797516-536a2d42-2e1a-11e8-8058-cacd4784ecb8.jpg)

It should be always present as issue https://github.com/consul/consul/issues/2320 described

**Comment by bertocq** [comment]
This is not good enough but it's close https://github.com/consul/consul/commit/1b63ba39d299a7bdda7465a31d78a733cb1136f3

- Styles inline will make @decabeza cry a river
- The text is not updated (the partial is not re-rendered) when max headings  value changes.. so full page refresh is needed 🙈 (tests should be updated to check it once that is also done)

**Comment by iagirre** [comment]
I'll go with this one.

**Comment by raul-fuentes** [comment]
I'll backport this one
