### ISSUE TITLE
Fix menu highlighted in admin section

### ISSUE THREAD

**Issue by voodoorai2000** [AyuntamientoMadrid/consul#1408]
### Steps to reproduce
Go to /admin
Click on different admin sections in the left sidebar

### Expected behaviour
- No menu should be highlighted by default
- Only the currently selected section should be highlighted once clicked

### Actual behaviour
- The Participatory Budget's menu is highlighted by default
- The currently selected section and Participatory Budget's menu links are highlighted

**Comment by aitbw** [comment]
I'm on it

**Comment by bertocq** [comment]
@aitbw this is not the behaviour we want, as explained to Itziar weeks ago. Issues should be closed manually when 100% completed, and in this case we need a backport to Consul to close this. Please avoid using `Closes #1408` syntax in PR descriptions 🙏 

I know some issues may be left open for more time than needed without it, but that's a better scenario than missing out a backport.

**Comment by aitbw** [comment]
Oh sorry @bertocq, I wasn't aware of it :ok_hand:

**Comment by aitbw** [comment]
Let's close this one as #1414 is already merged and its "backport" is ready at #2714
