### ISSUE TITLE
Unify background colour for "create" buttons in admin panel

### ISSUE THREAD

**Issue by bertocq** [AyuntamientoMadrid/consul#1416]
Thanks to @aitbw at https://github.com/AyuntamientoMadrid/consul/pull/1415 we noticed that "Create" buttons in the admin panels use blue and green background without any pattern/reason behind, creating inconsistency.

Background
==
Right now:
- Blue buttons /admin/budgets, /admin/newsletters and /admin/admin_notifications 
- Green buttons /admin/banners /admin/geozones /admin/tags /admin/legislation/processes 

![screen shot 2018-04-09 at 21 18 08](https://user-images.githubusercontent.com/983242/38518253-b8156308-3c3c-11e8-842e-434716c23355.jpg)
![screen shot 2018-04-09 at 21 18 06](https://user-images.githubusercontent.com/983242/38518255-b840c778-3c3c-11e8-93ba-da93b61b5ee3.jpg)
![screen shot 2018-04-09 at 21 18 04](https://user-images.githubusercontent.com/983242/38518256-b86eff26-3c3c-11e8-8ab4-eae6a85722d2.jpg)
![screen shot 2018-04-09 at 21 17 32](https://user-images.githubusercontent.com/983242/38518257-b8a7dd50-3c3c-11e8-91cd-53d17891321c.jpg)
![screen shot 2018-04-09 at 21 17 30](https://user-images.githubusercontent.com/983242/38518258-b8d11490-3c3c-11e8-8c0f-736b1a995e9b.jpg)

What we need
==

Adds consistency on admin buttons colors following this styles:

![admin_buttons](https://user-images.githubusercontent.com/631897/38570183-8d16adb8-3ced-11e8-8b61-69a8d9c902e7.png)

**Comment by aitbw** [comment]
I tend to associate the green color with life, creation so I think, UX-wise, it should be the default color for buttons when you want to create a new record —blue seems more like you want to offer the user more information about something

**Comment by decabeza** [comment]
Hi @bertocq and @aitbw! Thanks for the issue! 🙏 Definitely consistency is the key! 😌 

I updated the issue description with a "mini-guide" for buttons on Admin.

**Comment by bertocq** [comment]
Awesome @decabeza thats a great reference! Should that go into docs repo? 🤔 don't want to forget/loose it :)
