### ISSUE TITLE
Add year to Signature Sheets's dates in the admin section

### ISSUE THREAD

**Issue by MariaCheca** [AyuntamientoMadrid/consul#1427]
In the Signature Sheets admin section:
- Add year in the "Creation date" value showed in the index and show pages.
- Order index list by `created_at DESC`

**Comment by mlovic** [comment]
I'll backport this to consul/consul

**Comment by decabeza** [comment]
Closed by https://github.com/AyuntamientoMadrid/consul/pull/1428
