### ISSUE TITLE
Blacklist Bingbot by default

### ISSUE THREAD

**Issue by bertocq** [AyuntamientoMadrid/consul#1434]
We're getting a lot of "crap" traffic and rollbar errors from bingbot. And we're not alone https://meta.discourse.org/t/bingbot-is-default-throttled/84620

Blacklisting bingbot by default could be a great improvement for consul installations, with a clear documentation warning for those that might like to be indexed in such search engine

**Comment by raul-fuentes** [comment]
I'll do this one

**Comment by voodoorai2000** [comment]
👍

**Comment by raul-fuentes** [comment]
Maybe it would be interesting to use a setting to be indexed by bing, and it would not be too complicated

**Comment by voodoorai2000** [comment]
Sure +1 👍
