### ISSUE TITLE
Select if user account with a role can be verifiable 

### ISSUE THREAD

**Issue by decabeza** [AyuntamientoMadrid/consul#1436]
Background
==

Now on "Profiles" menu on admin panel, administrators can assign different roles to registered users like: officials, moderators, managers...

What we need
==

Add a checkbox when assigning these roles to confirm if the user account can be verifiable.

Also, we need to include a message on `/account` to inform the account can't be verifiable and disable "Verify my account" button.

Notes
==

We need to make a list of all actual users with a role and a verified account to contact them.

Screenshots
==

![screen shot 2018-04-18 at 14 01 44](https://user-images.githubusercontent.com/631897/38930807-76586e5c-4311-11e8-8ba0-aead12232e58.png)

![screen shot 2018-04-18 at 14 02 47](https://user-images.githubusercontent.com/631897/38930815-79230304-4311-11e8-83d2-fc731c029f52.png)

![screen shot 2018-04-18 at 14 04 05](https://user-images.githubusercontent.com/631897/38930819-7a74a5a0-4311-11e8-9572-950e5b86fb5e.png)

**Comment by iagirre** [comment]
I'll go with this.

**Comment by iagirre** [comment]
Two questions.
1. The checkbox to make the account verifiable should be added to the search list and index list or only to search?
2. The list of the users with a role and a verified account is something that should be added to the admins section (like a filter or something like that) or an external list appart from the page?

**Comment by decabeza** [comment]
Hi @iagirre,

1. Please add the checkbox **only on edit view** (show the info on search and index list, but should be enabled/disabled only on edit view) 

2. Don't worry about this list (we'll extract the list from the production database), it's something totally external to app.

😉

**Comment by bertocq** [comment]
@iagirre Please abandon this issue, the requirements are not meeting the problem behind (neither it was clearly explained). We'll do some research and definition and describe everything right again later on.

Take any issue with PR's-welcome label, as those are normally all well defined, and can be done by any external contributor to the core maintainer team.
