### ISSUE TITLE
Complete System Emails list on admin panel

### ISSUE THREAD

**Issue by bertocq** [AyuntamientoMadrid/consul#1437]
After https://github.com/AyuntamientoMadrid/consul/pull/1425 is merged, the admin will be able to view all system email templates. There are still many pending to be added to the list (check WIP commit https://github.com/AyuntamientoMadrid/consul/commit/bcf2dad383ddcaa150d5ebacef95a3613d98684b)

But as mentioned at https://github.com/AyuntamientoMadrid/consul/pull/1425/commits/570ed6a5ae7b68c43b86627e091e5d7b00bf1075 right now many of the View actions will fail if there are no records in the database to serve as example (Proposals, Investments, ProposalNotifications....)

So previously to completing the list that should be solved, by allowing the templates to either receive an object or plain text for each of the placeholders.

Additionally it would be great for the admins that want to understand which parts of the templates are placeholders if a third action "View Template" could be added, and for any of the texts the values would be something like **`{user_name}`** or **`{proposal_title}`**

**Comment by decabeza** [comment]
Closed by https://github.com/AyuntamientoMadrid/consul/pull/1892 🎉
