### ISSUE TITLE
Pleno Abierto

### ISSUE THREAD

**Issue by voodoorai2000** [AyuntamientoMadrid/consul#145]
- [x] Debemos crear una página de información relacionada con el 'Pleno Abierto'.
- [x] Desde esta página deberían haber dos links/botones para crear debates y propuestas respectivamente.
- [x] Al crear un debate/propuesta la etiqueta "plenoabierto" deberá estar autorellenada
- [x] Desde la página de bienvenida deberán haber dos links para navegar respectivamente por todos los debates y propuestas etiquetados con "plenoabierto"

**Comment by decabeza** [comment]
Already done! 🎉
