### ISSUE TITLE
Fix exception when visiting followed proposals

### ISSUE THREAD

**Issue by voodoorai2000** [AyuntamientoMadrid/consul#1462]
Steps to reproduce
===
Click on 'My activity'
Click on 'Following'

Expected Behaviour
===
I should see the proposals that I follow

Actual Behaviour
===
An exception is raised

Notes
===
Production example: https://decide.madrid.es/users/138?filter=follows&page=1
Related exception: https://rollbar.com/consul/Participacion/items/1488/

**Comment by decabeza** [comment]
Closed by https://github.com/AyuntamientoMadrid/consul/pull/1466
