### ISSUE TITLE
Moderate pending proposal system emails

### ISSUE THREAD

**Issue by MariaCheca** [AyuntamientoMadrid/consul#1468]
Context
=========
A proposal's author can send notifications to its supporters. Those notifications awaiting to be sent are available in the view `/admin/system_emails/proposal_notification_digest/preview_pending` for admins to review them.

What
=========
A button is needed for each notification email with the text "Moderate notification sending". When the button is clicked the notification will be removed. Also it should appear in the Moderation section.

How
========
- Add moderation abilities for Notifications.
- Add new tab "System emails" in the Moderation section `/admin/activity`.

**Comment by decabeza** [comment]
Closed by https://github.com/AyuntamientoMadrid/consul/pull/1471
