### ISSUE TITLE
Activity feed: handling actionable attributes 

### ISSUE THREAD

**Issue by MariaCheca** [AyuntamientoMadrid/consul#1480]
Context
=======
Admin activity feed (`admin/activity`) shows actions performed by moderators over some objects like Proposals, Debates, etc, called `actionable` in the `Activity` environment. 

What
=======
```
NoMethodError: undefined method `title' for #<Newsletter:0x0000000eca9e10>
```
In the code there are assumptions about the actionables attributes, and for `Newsletters` the attribute `title` doesn't exists, so when the [list view](https://github.com/AyuntamientoMadrid/consul/blob/master/app/views/admin/activity/show.html.erb#L37) tries to render these actionables returns the error above.

We need to fix it and let it choose what attribute has to be called.

**Comment by decabeza** [comment]
Closed by https://github.com/AyuntamientoMadrid/consul/pull/1481
