### ISSUE TITLE
Database left "dirty" after model spec

### ISSUE THREAD

**Issue by mlovic** [AyuntamientoMadrid/consul#1581]
While doing backports, I noticed the [`spec/models/budget/stats_spec.rb`](https://github.com/AyuntamientoMadrid/consul/blob/master/spec/models/budget/stats_spec.rb) spec creates records without deleting them afterwards. This can cause order-dependent failures in other tests which expect to be run on a "clean" database, e.g. https://travis-ci.org/AyuntamientoMadrid/consul/jobs/407285928, which can be reproduced with:

    bin/rspec --order defined spec/models/budget/stats_spec.rb:49 spec/features/polls/results_spec.rb:4

The reason this happens is that model specs use the `:transaction` strategy, which wraps each individual example (including `before(:each)` hooks) in a transaction which is then rolled back. The `before(:all)` hook is not wrapped in a transaction so it is never rolled back.

We probably need to either:
 - avoid `before(:all)` in favor of `before(:each)` (at the expense of slower tests)
 - clean up manually in a `after(:all)` hook, either clearing each model individually or running DatabaseCleaner with the truncation strategy

As far as I can tell, this is the only `before(:all)` hook in the codebase.

I would be happy to do this!

**Comment by mlovic** [comment]
Actually, using `before(:each)` causes another problem:

Some of the code depends on the heading `id` being `1` (https://github.com/AyuntamientoMadrid/consul/blob/master/app/models/budget/ballot/line.rb#L48). Because of SQL auto-increment, this is only the case the first time the hook is run. All subsequent runs fail.

**Comment by javierm** [comment]
This issue isn't present in the main CONSUL repository nor is most of the related code, so closed by #1597.
