### ISSUE TITLE
Translatable form locale selection: tab becomes incorrectly highlighted when clicking parent element

### ISSUE THREAD

**Issue by mlovic** [AyuntamientoMadrid/consul#1616]
### Description

*Type*: Bug

### Current Behavior

In any translatable form, there is `<ul>` of `<li>`s acting as tabs, one for each locale, each with a `<a>` element inside. 

When clicking on the `li` element, but outside the inner `a` element, the locale tab acquires the `is-active` class (and becomes visibly highlighted), but this does not trigger the right globalize JS callback.

See below: the first clicks (to the side of the link text) demonstrate this behaviour. The last clicks (on the link text) demonstrate the expected behaviour.

![is_active_bug](https://user-images.githubusercontent.com/7111622/44671147-f2920300-aa24-11e8-9ad7-87ce16972c30.gif)

### Expected Behavior
Either:
 - clicking outside of the link text should not highlight the selected tab
OR
 - clicking outside of the link tetx should have the same behaviour as clicking on the link text, i.e. other tabs are un-selected and the active locale is changed.

### Steps to reproduce

See GIF above. This works on any translatable form, e.g. http://localhost:3000/admin/budgets/budget-2018/budget_investments/74/budget_investment_milestones/151/edit.

### Additional info

Clicking on the `li` element (not the inner `a` element), adds the `is-active` class to the parent `li` element, instead of the `a` element like is expected. I think this might be part of the default behaviour of [Foundation tabs](https://foundation.zurb.com/sites/docs/v/5.5.3/components/tabs.html). The behavior persists even after removing the `/home/marko/consul/app/assets/javascripts/globalize.js.coffee` file.

**Comment by javierm** [comment]
Closed via #1710.
