### ISSUE TITLE
Saltos de línea en comentarios

### ISSUE THREAD

**Issue by estufa8** [AyuntamientoMadrid/consul#295]
Después de escribir un comentario largo, con sus párrafos, etc, es una pena descubrir que una vez publicado se muestra todo seguido. Eso puede aburrir o ahuyentar al lector ante semejante tocho.
En una aplicación creada entre otras cosas para esto: comentar, lo encuentro un fallo notable.
Además parece algo sencillo de solucionar.
Por lo demás, enhorabuena!

**Comment by ManjiChiba** [comment]
No es que sea muy importante, pero, también estaría bien poder utilizar la tabulación y no tener que hacerlo dándole varias veces al espacio.
Ej de lo que menciono:
https://decide.madrid.es/proposals/8938-recopilacion-de-propuestas-relativas-a-mejora-de-la-administracion-de-la-web-1
Es una chorradilla, pero todo suma.

**Comment by estufa8** [comment]
mil gracias xuanxu, que apañao
