### ISSUE TITLE
Que se aumente el número de mensajes privados diarios a 50.

### ISSUE THREAD

**Issue by ManjiChiba** [AyuntamientoMadrid/consul#319]
30 se quedan muy cortos.

**Comment by xuanxu** [comment]
Se estableció 30 como un número alto, que de momento no es alcanzado por prácticamente ningún usuario, en cuyo caso se revisaría. Para mantener conversaciones largas, la idea es que los usuarios pasen a contactarse por email.

**Comment by ManjiChiba** [comment]
Ok. Que le vamos a hacer, tendré que posponer lo de ir reagrupando propuestas para más adelante.
