### ISSUE TITLE
Boton Retirar, también dentro de la propia propuesta

### ISSUE THREAD

**Issue by ManjiChiba** [AyuntamientoMadrid/consul#334]
No es que sea importante ni urgente, pero ayudaría.
https://decide.madrid.es/proposals/13157-boton-retirar-tambien-dentro-de-la-propia-propuesta

**Comment by xuanxu** [comment]
Descartado por sobrecarga de acciones en el interfaz

**Comment by ManjiChiba** [comment]
Ok. Como veáis, yo era por ir eliminando bastantes de las mías, para no saturar la BBDD. Es que si tengo que ir buscándolas 1x1... pufff.
