### ISSUE TITLE
Mensajes privados con posibilidad de Punto y Aparte

### ISSUE THREAD

**Issue by ManjiChiba** [AyuntamientoMadrid/consul#387]
Actualmente en los mensajes privados, aunque se cree haciendo puntos y aparte y saltos de línea, a la hora de enviarlo, aparece como si lo juntara todo, sin respectar los saltos de línea.

**Comment by ManjiChiba** [comment]
Por cierto, agradecería alguna explicación ANTES de cerrar la propuesta (o incluso, después).

**Comment by decabeza** [comment]
Cierro porque esto se ha arreglado con la PR consul#1247

**Comment by ManjiChiba** [comment]
Sí, efectivamente, ya esta solucionado y he dejado constancia del trabajo que habéis realizado en:
Recopilación de Propuestas relativas a Mejora de la Administración de la web 2.
	https://decide.madrid.es/proposals/11947
Este Issue lo podéis incluso borrar si lo veis necesario.
Ya no tiene razón de permanecer.
