### ISSUE TITLE
Poder enviar un mensaje privado conjunto en vez de (o junto a) "notificación".

### ISSUE THREAD

**Issue by ManjiChiba** [AyuntamientoMadrid/consul#389]
En primer lugar, me gustaría agradecer a los administradores de la web, la relativa "nueva" opción de notificación.

Es útil y una muy buena idea, pero.... tengo comprobado que NO es todo lo eficaz que esperaba (¿se esperaba?).

Sí, es cierto, que se envía un mensaje/notificación a todos los usuarios que han apoyado una propuesta, pero también tengo comprobado que la mayoría de las personas no la leen porque NO SABEN donde está / encontrarla (el que esté en una pestaña al lado de los "Comentarios", hace que la mayoría no llegue a verla/visitarla).

Propongo que aparte de la notificación (que se ha revelado como poco eficaz), se envíe un Mensaje Privado (como el resto de mensajes privados), con el mismo contenido que la notificación.

Creo que este mensaje SI tendría visibilidad directa y ayudaría mucho a la re-agrupación de propuestas sin que se pierdan apoyos (como está ocurriendo actualmente).

Se agradecería que esta vez se me comentara algo antes de cerrar la propuesta sin ninguna explicación.
Gracias anticipadas.

**Comment by voodoorai2000** [comment]
Gracias por la sugerencia @ManjiChiba, en lugar de mandar mensajes directos (emails) sobre cada notificación, periódicamente mandamos un Email Digest con todas las notificaciones de los autores de propuestas a los usuarios que han votado esas propuestas. 

Ya hemos enviado un par, antes de final de año mandaremos otra. Creemos que es mejor agrupar las notificaciones para no saturar a los usuarios.
