### ISSUE TITLE
Que NO se puedan borrar propuestas superiores al año con más de 100 apoyos.

### ISSUE THREAD

**Issue by ManjiChiba** [AyuntamientoMadrid/consul#390]
Ya se, que seguramente/posiblemente esto no sea atribuciones del equipo de desarrollo, pero esta creando muchísimo malestar el que se estén trasladando propuestas a la sub-sección archivadas.
Lo que más "cabreo" está generando es que se haya pasado (y ya no se puedan apoyar), propuestas que tenían más de 100 apoyos (no digamos las que superan los 1.000).
Entiendo que pueda ser una decisión "política", pero aquí lo dejo comentado (estas cosas, SI son de las que hacen perder votos).

**Comment by ManjiChiba** [comment]
Agradeceré algún comentario antes de cerrar esta sugerencia.

**Comment by voodoorai2000** [comment]
La directriz del Ayuntamiento que regula este proceso establece este periodo de caducidad.
