### ISSUE TITLE
Botón abstención ("en contra").

### ISSUE THREAD

**Issue by ManjiChiba** [AyuntamientoMadrid/consul#391]
Creo que podría ser interesante un nuevo botón de abstención, pues así se podría saber, cuantas personas han visitado el post, aunque luego, no les haya convencido la propuesta para apoyarla, o, en el caso de los debates si no está a favor, ni en contra.

Actualmente, se puede saber cuantas personas han apoyado una propuesta, pero no, cuantas personas la han visto (¿talvez haya mucha gente que visita la web, pero pocos se animan a apoyar las propuestas?).

También podría dar una idea aproximada "más real", de cual es la aceptación o "rechazo" de una propuesta, o incluso, inducir a su creador a retirarla, por falta de suficiente apoyo (muchas abstenciones vs pocos apoyos).

Es evidente, que las personas que estuvieran en contra, pulsarían "abstención", que si bien NO es lo que les gustaría "votar", si dejaría constancia de que:

a) Han visitado la propuesta.

b) NO están de acuerdo con ella (o bien les es indiferente DESPUES de haberla leído, o bien están en contra).

Agradecería algún comentario explicativo antes del cierre de la propuesta.

**Comment by voodoorai2000** [comment]
Gracias por la sugerencia @ManjiChiba, lo hemos sopesado pero no vemos que aporte una ventaja ahora mismo.
