### ISSUE TITLE
Sub-secciones para distritos para que no se quite visibilidad a otras propts.

### ISSUE THREAD

**Issue by ManjiChiba** [AyuntamientoMadrid/consul#392]
Lo desarrollo al completo en la propuesta.

https://decide.madrid.es/proposals/5994-sub-secciones-para-distritos-para-que-no-se-quite-visibilidad-a-otras-propts

Si es cierto, que para esta propuesta resulte interesante, tendría que llevarse a la práctica antes, esta otra:
- Reducir a 2.500 apoyos el límite para las propuestas de Distrito.
https://decide.madrid.es/proposals/11996
Una vez llevada a la práctica esta propuesta, si me podría animar a ir invitando a todos los usuarios a ir desplazando voluntariamente sus propuestas al Distrito correspondiente, así como animarles a reagrupar e ir borrando aquellas que estén repetidas.

Agradecería algún comentario antes del cierre de la sugerencia.

**Comment by ManjiChiba** [comment]
Si es cierto, que para esta propuesta resulte interesante, tendría que llevarse a la práctica antes, esta otra:
Reducir a 2.500 apoyos el límite para las propuestas de Distrito. (53 apoyos)
     https://decide.madrid.es/proposals/11996
Una vez llevada a la práctica esta propuesta, si me podría animar a invitando a todos los usuarios a ir desplazando voluntariamente sus propuestas al Distrito correspondiente, así como animarles a reagrupar e ir borrando aquellas que estén repetidas.

**Comment by voodoorai2000** [comment]
Queremos darle visibilidad a las propuestas de distrito, por eso las mantenemos accesibles desde la misma página.

**Comment by decabeza** [comment]
Además, para "filtrar" por distrito existe una página para ello: https://decide.madrid.es/proposals/map

![screen shot 2016-10-19 at 11 53 07 2](https://cloud.githubusercontent.com/assets/631897/19514105/b053bc24-95f2-11e6-9324-ab03c21d4d8d.png)
