### ISSUE TITLE
Recopilación de Propuestas relativas a Mejora de la Administración de la web 1 y 2.

### ISSUE THREAD

**Issue by ManjiChiba** [AyuntamientoMadrid/consul#393]
Evaluar las Propuestas recogidas en estos 2 Recopilatorios (iré haciendo un issue por cada una de ellas cuando tenga más tiempo).
Recopilación de Propuestas relativas a Mejora de la Administración de la web 1.
	https://decide.madrid.es/proposals/8938
Recopilación de Propuestas relativas a Mejora de la Administración de la web 2.
	https://decide.madrid.es/proposals/11947

**Comment by xuanxu** [comment]
Esto son propuestas de funcionamiento de decide madrid que pertenecen a los administradores y gestores del area de participación. No es tema técnico, cierro.

**Comment by ManjiChiba** [comment]
¿Cómo o donde podría ponerme en contacto con los administradores?.
