### ISSUE TITLE
Que se puedan borrar los debates igual que se pueden borrar las Propuestas.

### ISSUE THREAD

**Issue by ManjiChiba** [AyuntamientoMadrid/consul#446]
Que se puedan borrar los debates PROPIOS igual que se pueden borrar las Propuestas. 

Muchos debates, al pasar a convertirse en propuesta, pueden parecernos que ya sobran (aunque si ha habido un debate constructivo, es más interesante dejar un enlace en la propuesta al debate para ver las conclusiones a las que se llegaron, pero vamos, que el 99% de los "debates" sólo son una algarabía de "en contra" y "a favor", en vez de "formas de mejorar, redactar y completar una futura propuesta" que era su intención inicial -un paso previo a poner la propuesta-).

Otros debates, simplemente, se quedan obsoletos y ya no tienen razón de ser (por ejemplo, para pedir cosas para una fecha concreta, porque ya se han llevado a la práctica... etc).

Yo borraría un par de ellos ya.

Más concretamente.
https://decide.madrid.es/debates/4871-a-vueltas-con-el-ibi-y-demas-impuestos
Ya que por el momento no se pueden borrar, quería haberlo editado para borrar el contenido, pero no he podido, porque NO se puede editar, mientras esté marcado como inapropiado (aunque solo lo hayan hecho de manera arbitaria y para fastidiar, los mismo 15-20 de siempre que no terminan de irse de la web).

Gracias anticipadas.

**Comment by xuanxu** [comment]
Cuando en un debate hay gente participando se considera que ya no es de quien lo creó sino una discusión colectiva, por tanto no se puede borrar.

**Comment by ManjiChiba** [comment]
Ok. Por mi parte no hay problema, era más por ir limpiando alguno y que no vaya creciendo más la BBDD.
Se puede cerrar ya esta Issue entonces (por lo que a mi respecta).
