### ISSUE TITLE
Facilitar el agrupamiento.

### ISSUE THREAD

**Issue by ManjiChiba** [AyuntamientoMadrid/consul#448]
Por mi parte, poco a poco, estoy intentando agrupar propuestas similares y que se borren las repetidas, pero.... es que con las pocas herramientas de que dispongo (Mensaje Privado y Notificaciones), es un calvario, un trabajo de Chinos, aparte de todos los apoyos que se pierden por el camino (entre un 80%-90).
Facilitará muy mucho, estudiaran las 2 siguientes posibilidades:
1º Poder enviar un mensaje privado conjunto en vez de (o junto a) "notificación".
     https://decide.madrid.es/proposals/13855
Actualmente, casi nadie sabe donde localizar el tema de la notificación (yo, la 1ª vez tarde en darme cuenta de que ponía "Ha recibido una nueva Notificación" y no "Ha recibido un nuevo Mensaje"), puesto que casi nadie sabe que es una pestaña al lado de la Comentarios (tiene una visibilidad muy reducida).
Creo que sería más llamatido acompañarla de un Mensaje Privado con el mismo texto, pues la campanita encendida en amarillo o el nuevo pop-up azul "Propuesta actualizada correctamente" que se abre cuando modificas una propuesta SI llaman mucho la atención y NO pasan desapercibidos).
Es que se pierden casi todos los apoyos al agrupar propuestas avisando mediante notificación, porque poca gente se entera o ve la notificación.
2º Poder adoptar propuestas cuyos autores las han abandonado (con el permiso del administrador). (6 apoyos). https://decide.madrid.es/proposals/10043
Esto permitiría que NO se perdieran apoyos en los traspasos o adopciones de propuestas.

**Comment by xuanxu** [comment]
Todas las notificaciones se envian también como mensajes privados a los usuarios que así lo configuran en 'Mi cuenta'.

**Comment by ManjiChiba** [comment]
Yo me refiero a que el usuario pueda recibir un mensaje privado directamente con el texto/contenido de la notificación, no que tenga que buscar el texto de la notificación dentro de la propuesta (la mayoría no tiene ni idea de donde se pueden ver las notificaciones).
