### ISSUE TITLE
Que se puedan bloquear a usuarios en las propuestas propias.

### ISSUE THREAD

**Issue by ManjiChiba** [AyuntamientoMadrid/consul#449]
Sería ideal poder bloquear en cada propuesta y de manera separada comentarios de terminados usuarios, o si técnicamente es complicada para cada propuesta de manera independiente, al menos, en todas ellas a la vez para una lista de usuarios (blacklists/whitelists las suelen llamar).
Obviamente, me refiero a "en las propuestas propias".
En fin, espero que tenga esta petición en consideración.

**Comment by ManjiChiba** [comment]
Ya he visto el trabajo realizado en este aspecto. 10/10
Gracias.

**Comment by decabeza** [comment]
Closed in favor of https://github.com/consul/consul/issues/2423
