### ISSUE TITLE
Ahorrar trabajo a los administradores.

### ISSUE THREAD

**Issue by ManjiChiba** [AyuntamientoMadrid/consul#478]
Creo que los Administradores ya tienen suficiente trabajo como para tener que ir perdiendo su valioso tiempo, desmarcando 1x1 todos los debates y propuestas que hago, ya que, todas, cada una, siempre se van marcando arbitrariamente POR LOS MISMOS SUJETOS 1x1.
Sólo tendrían que comprobar que los que las marcan como inapropiadas, SIEMPRES SON LOS MISMOS, los 15-20 trolls de La Manada.
Hasta ahora, y como era un tema que sólo afectaba a las propuestas, y en vista de que pasado un tiempo, se revisaban esas marcas arbitrarias (y sin justificación ninguna) y se quitaban (trabajo repetitivo y adicional para los administradores), no he querido insistir con este tema (aunque me parece una "cabronada" el estar generando ese trabajo adicional a los Administradores por capricho de una veintena de trolls furibundos de los de "que dimita tal", "que dimita cual", etc).
El problema es que TAMBIEN están marcando/boicoteando los debates que creo, ya que al marcarlos arbitrariamente como inapropiados, ya no puedo editarlos para tener en cuenta las sugerencias del resto de madrileños/as.
Un Ej: https://decide.madrid.es/debates/4914-nuevas-etiquetas
y creo que, en esta ocasión, NO es solamente una apreciación personal y única.
https://decide.madrid.es/proposals/7391-muerto-el-perro
https://decide.madrid.es/proposals/7629-es-normal-que-la-gente-entre-a-las-propuestas-para-boicotearlas
Posiblemente esto no vaya aquí, pero es que no he visto donde puedo ponerme en contacto (e-mail) con los Administradores para comentarles este tema (que me imagino, les interesa, pues les concierne, por el trabajo adicional que les genera).

**Comment by xuanxu** [comment]
No podemos atender esta petición porque este no es un foro de administradores de decide madrid, sino el listado de problemas tecnicos para los desarrolladores del código.

**Comment by ManjiChiba** [comment]
Si me podéis indicar donde me puedo poner en contacto con los administradores o estaría agradecidos (he estado buscando en la web y no he encontrado el sitio a donde dirigir estas sugerencias relativas a la admnistración del site).
