### ISSUE TITLE
¿Nuevas etiquetas?

### ISSUE THREAD

**Issue by ManjiChiba** [AyuntamientoMadrid/consul#480]
Creo que es algo fácil de implementar, ¿no? (es decir, implica muy poco trabajo añadir unas cuantas más, y se demuestra que se está trabajando duro por mejorar la web).
He propuesto estas a la espera de las que puedan comentar los ciudadanos.

https://decide.madrid.es/proposals/14966-nuevas-etiquetas-sugerencias

Obviamente son sugerencias, los administradores sabrán mejor cuales pueden ser interesantes y cuales no, porque, supongo, manejarán sus propias estadísticas.
Las etiquetas del grupo de Categorías, ¿están pre-definidas, o se generan de manera dinámica según la cantidad de veces que se repiten?.

**Comment by xuanxu** [comment]
Esto es decisión de los administradores, el software permite añadir cualquier etiqueta.

**Comment by ManjiChiba** [comment]
Ok. Pero... ¿hay algún foro de administración donde se lo pueda comentar?
