### ISSUE TITLE
Poder "subir" las propuestas a las primeras posiciones para ganar visibilidad.

### ISSUE THREAD

**Issue by ManjiChiba** [AyuntamientoMadrid/consul#481]
Creo que es algo fácil de implementar, ¿no? (es decir, implica muy poco trabajo añadir unas cuantas más, y se demuestra que se está trabajando duro por mejorar la web).
Creo que no es muy complicado de hacer (proporción esfuerzo/resultados de mejora).
Sería algo fácilmente apreciable por los ciudadanos y (creo), no implica mucho trabajo de programación (aunque, obviamente, puedo estar equivocado).
https://decide.madrid.es/proposals/11282-poder-subir-las-propuestas-a-las-primeras-posiciones-para-ganar-visibilidad

**Comment by xuanxu** [comment]
Funcionalidad descartada.
