### ISSUE TITLE
Cambiar la opción notificación para que también se haga con un Mensaje Privado

### ISSUE THREAD

**Issue by ManjiChiba** [AyuntamientoMadrid/consul#482]
Creo que es algo que sería fácil de implementar (poco trabajo) y sería muy valorado por los ciudadanos, ya que permitiría poder agrupar las propuestas con mayor facilidad (actualmente, la notificación tiene poca o nula visibilidad donde esta).
https://decide.madrid.es/proposals/12948
Creo que la proporción trabajo / mejora es muy bueno (poco trabajo / mucha mejora)

**Comment by xuanxu** [comment]
Todas las notificaciones se envian también como mensajes privados a los usuarios que así lo configuran en 'Mi cuenta'.

**Comment by ManjiChiba** [comment]
Sí, a lo mejor no me he explicado bien.
A lo que me refiero, es que hay poca diferencia en la cabeceras entre "Tiene un nuevo mensaje" y "Tiene una nueva notificación".
Por otra parte, tengo la impresión, que un alto índice de usuarios, ni siquiera sabe lo que es una notificación, ni en que parte de la interfaz la pueden encontrar y leer (a mi me costo bastante fijarme la 1ª vez).
En los mensajes, cuando es de respuesta a un comentario, te posiciona automáticamente en la parte del comentario, sin que tengas que buscarlo entre todos ellos, e incluso puedes responder directamente sin ir a la propuesta.
El tema de las notificaciones es fundamental para poder ir agrupando propuestas sin que se pierdan apoyos por el camino (como ocurre actualmente).
Cuando tenga un momento pongo capturas de a lo que me refiero (se entiende mejor de forma gráfica).
