### ISSUE TITLE
 Aviso por mensaje de que una Propuesta ha pasado a 3ª fase.

### ISSUE THREAD

**Issue by ManjiChiba** [AyuntamientoMadrid/consul#483]
Otra idea, que creo implicaría muy poco trabajo (a lo mejor me equivoco), y una gran valoración por parte de los ciudadanos sobre lo duro que se está trabajando para mejorar la web.

https://decide.madrid.es/proposals/8704

Creo que implica muy pocos recursos y esfuerzos y sería fácilmente apreciable.

**Comment by decabeza** [comment]
Estamos trabajando en la nueva funcionalidad "Panel de control de propuestas" consul#2981 que permitirá a los autores tener una visión de como está funcionando su propuesta y ver esta información. :)
