### ISSUE TITLE
Ahorrar trabajo a los administradores. 2

### ISSUE THREAD

**Issue by ManjiChiba** [AyuntamientoMadrid/consul#484]
Creo que esta medida
Justificar las marcas que se hagan de Inapropiados.
     https://decide.madrid.es/proposals/7391
podría ahorrar mucho trabajo a los administradores.
Por lo menos, en mi caso, les toca ir detrás de cada una de las propuesta y debates que abro, quitando dichas marcas (y siempre son los mismos los que las marcan, un minoritario grupo de trolls/franquistas que me la tienen jurada).
Si no.... pues no pasa nada, para mi no es grave, ni urgente.
Por suerte, parece que los trolls, prácticamente ya han desaparecido o por lo menos, no se dedican a enfangar la web.

**Comment by ManjiChiba** [comment]
Vaya por delante que no me parece grave (en este caso), que se haya cerrado el issue sin ni siquiera una respuesta ni nada de nada, pero....
Cuando yo he trabajado en servicios técnicos donde teníamos que resolver incidencias, no podíamos cerrar una incidencia si el afectado no manifestaba explícitamente que ya estaba resuelta.
Me parece que es como si vas a hablar con alguien en la puerta de su casa y nada más abrir la boca, te dan con la puerta en las narices.
Me parece un gesto poco... amable.

**Comment by xuanxu** [comment]
Esto no es el servicio técnico ni de resolución de incidencias de la web. Es el panel de comunicación de los desarrolladores del proyecto de software en el que se basa la web.

Es como si no te cuadraran los horarios o las rutas de los autobuses de la EMT y fueras a pedir que los cambiaran al taller mecánico en el que se fabrican y reparan los autobuses. A veces los mecánicos están muuy liados y tienen mucho trabajo acumulado, perdonales si tardan en responder o cierran issues sin avisar, no hay mala intención por su parte :)

**Comment by ManjiChiba** [comment]
No, a ver, no me mal-interpretéis, es que desconozco a donde (o en donde) debo dirigirme para ponerme en contacto con los administradores y en la web no he visto a donde debería dirigirme para ello.
He puesto algún comentario a alguno de ellos, pero no han respondido, y no hay posibilidad de enviarles un mensaje privado (parecen masones o una secta secreta o algo así).
Si lo supiera no molestaría (habría molestado aquí).
Disculpen las molestias.
