### ISSUE TITLE
Que se puedan editar los debates igual que se pueden editar las Propuestas.

### ISSUE THREAD

**Issue by ManjiChiba** [AyuntamientoMadrid/consul#485]
Ya se que ahora se está muy ocupado con los temas de los recientes Presupuestos Participativos y la futura votación de las 2 1as propuestas que se van a poder votar, pero...
creo que esta es otra de esas propuestas que implica muy poco trabajo (entiendo que si ya se puede hacer en las propuestas, no será muy complicado copiarlo para los debates)
Que se puedan editar los debates igual que se pueden editar las Propuestas.
     https://decide.madrid.es/proposals/12110
No es que sea una cosa urgente, pero como creo que es algo sencillo y que tendría visibilidad del trabajo realizado...

**Comment by xuanxu** [comment]
Los debates ya son editables hasta que se consigue algún apoyo

**Comment by ManjiChiba** [comment]
Mis dudas son:
a) ¿hasta que recibe 1 apoyo?, ¿¡luego ya no es editable (no se entonces como se va a corregir y mejorar la idea)¡?
b) Yo, el problema que tengo, es que si un debate está marcado como inapropiado, mientras esta marca permanezca, NO aparece el botón de editar (creo que serían casos diferentes).
En cualquiera de los 2 casos... si no se pueden editar los debates.... poca utilidad les veo entonces.

**Comment by xuanxu** [comment]
Lo de hasta que se consiga un apoyo es para que el autor pueda corregir faltas de ortografía o cosas menores de las que se de cuenta al crear el debate. Si se permitiera editar el texto cuando un debate tiene un 80% de votos favorables (por ejemplo) se podría modificar el texto para que significara algo totalmente distinto al debate original que recibió los apoyos. 

En cualquier caso, técnicamente el software permite poner el umbral en el número de apoyos que se quiera, son los administradores actuales los que han decidido que sea 1.

**Comment by ManjiChiba** [comment]
mmm, entiendo en parte lo que comentas, pero esa problemática la veo más asociada a las propuestas que a los debates.
Un debate puede recibir apoyos y rechazos (es más, puedes cambiar incluso el sentido de 1 a otro sin mayor complicación, lo cual, esta MUY BIEN pensado), y se supone que un debate es como un paso previo (una especie de sondeo y recogida de enmiendas, así lo he entendido yo) a formalizar la idea en una propuesta. 
No obliga, ni implica nada.
Otra cosa bien distinta, es en las propuestas, donde, como bien indicas, si podría darse el caso de algún troll "graciosete", que hiciera una propuesta y cuando estuviera cercana a conseguir los 27.000 apoyos (soñar no cuesta nada), cambiarle el cuerpo de la propuesta para que significara todo lo contrario.
Quizás ahí, SI, sería más lógico que a partir de determinado número de apoyos (¿un 50%? = 13.500) ya no se pudiera editar/cambiar la propuesta, o una opción alternativa como propongo yo en:
Permitir cancelar el apoyo a una propuesta. (87 apoyos)
     https://decide.madrid.es/proposals/11867
Que se notifique a las personas que apoyaron la propuesta, que dicha propuesta se ha modificado (cada vez que se modifique, aunque no se si los servidores de SMTP soportarían dicha carga) y que tienen un periodo de x horas (a determinar) en el que pueden retirar su apoyo si así lo consideran oportuno.
De hecho, algo similar ya ha ocurrido con una propuesta en Change.org.
Un ciudadano hizo una propuesta, que las personas apoyaron y consiguió los apoyos necesarios, pero.... el disgusto de las personas que apoyaron dicha propuesta fue grande, cuando resulto que no la va a presentar la misma persona que la propuso, si no que la va a "apadrinar" y "desarrollar legislativamente" Ciudanos, lo cual ha generado malestar y comentarios del estilo "quiero retirar mi apoyo", o "si llego a saber que era para que finalmente la manipulara Ciudadanos, no la hubiera apoyado", etc.
Espero haberme explicado bien (aunque esto sea más un tema de administradores que de desarrollo).
