### ISSUE TITLE
Corrector ortográfico en el cuerpo de las propuestas.

### ISSUE THREAD

**Issue by ManjiChiba** [AyuntamientoMadrid/consul#486]
Corrector ortográfico en el cuerpo de las propuestas.
     https://decide.madrid.es/proposals/14241

Actualmente ya está implementado en la cabecera y por ejemplo, también se ha implementado en los mensajes privados, pero creo que en los cuerpos de las propuestas o no está todavía, o si está, no está funcionando.
Sería algo, que, me imagino (a lo mejor, erróneamente), sería poco trabajo (¿copy and paste del código?), y tendría una clara visibilidad para el ciudadano, aparte, de que lo apreciaría rápidamente (no es como otras de mis sugerencias, que entiendo, SI serían más complicadas de llevar a la práctica y requerirían muchas horas de programación por ser muy ambiciosas).
Espero no les moleste mi sugerencia.

**Comment by xuanxu** [comment]
N¡El corrector ortográfico lo facilita el navegador, no es una funcionalidad de consul.

**Comment by ManjiChiba** [comment]
¿Y es normal que funcione en el resumen de la propuesta pero no en el cuerpo/desarrollo de la misma?
