### ISSUE TITLE
¿Errores de programación?

### ISSUE THREAD

**Issue by ManjiChiba** [AyuntamientoMadrid/consul#489]
Llevo un par de días que no puedo poner ningún comentario en ninguna propuesta.
Tampoco puedo crear propuestas nuevas.
Me sale este error
![error](https://cloud.githubusercontent.com/assets/16508522/21464452/61bf6f18-c97d-11e6-8f22-532893f880ed.jpg)
y en la web, no aparece ninguna dirección e-mail de contacto de ningún administrador (o al menos, yo no la he visto por ningún lado).
Gracias anticipadas.

**Comment by decabeza** [comment]
Hola @ManjiChiba, he podido acceder sin problemas a esa URL y también dejar un comentario.

![screen shot 2016-12-24 at 12 48 13](https://cloud.githubusercontent.com/assets/631897/21466848/781384ac-c9d7-11e6-80f0-4a8411b1b453.png)

![screen shot 2016-12-24 at 12 48 29](https://cloud.githubusercontent.com/assets/631897/21466849/7a4cc86e-c9d7-11e6-9c6b-7d43e3de2510.png)

¿Puedes confirmarme si ya puedes comentar/crear propuestas o si el problema continúa? 

¡Gracias!

**Comment by ManjiChiba** [comment]
Hace un rato que lo he probado, y para crear propuestas ya me deja, pero por ejemplo al editar, cuando le doy a guardar, me sigue apareciendo el mensaje y no actualiza.

**Comment by decabeza** [comment]
Hola @ManjiChiba parece que ese error viene determinado por tu proveedor de internet y no tiene relación con la página.

Puedes intentar solucionarlo con algo de lo que proponen aquí 😉 
http://stackoverflow.com/questions/8892197/how-to-resolve-the-requested-url-is-rejected-error

**Comment by ManjiChiba** [comment]
Por lo que he podido ver en las pruebas que he realizado, es algo sumamente raro y que yo creo que tiene que ver con algo en la programación o algo que se haya cambiado recientemente.
En primer lugar, NO deja poner enlaces en determinados sitios, pero si quitas el https:// SI te deja.
Ejemplo.
Así no deja.
http://stackoverflow.com/questions/8892197/how-to-resolve-the-requested-url-is-rejected-error
pero así, SI deja.
stackoverflow.com/questions/8892197/how-to-resolve-the-requested-url-is-rejected-error
Lo otro que ocurre, es que, cuando se hace copy/paste desde una hoja de word, por algún motivo que desconozco, da este error (o directamente NO deja enviar el comentario), sin embargo, cuando haces un copy/paste desde otra propuesta.... ¡boila!, funciona.
También funciona si en vez de copy/paste lo escribes de nuevo.
Antes no pasaba esto, es más, no se como esta/tenéis programada la página web, pero antes, era como si hicieras el copy/paste de la fuente que lo hicieras (un documento word o desde otra propuesta que utilizaras como plantilla), luego, internamente, convirtiera todo a un mismo tipo de letra (fuente), y a la hora de publicarse salía todo con el mismo tipo de letra.
Ahora parece ser que ya no va así (¿algún cambio?), parece que ya no hiciera esa conversión de tipos de letras (fuentes) y es lo que genera este extraño error, o que no se puedan enviar los comentarios.
NO es nada relacionado con el proveedor, ni con las cookies.
Ya he hecho pruebas con el proveedor, y es independiente del proveedor, el error ocurre siempre, utilices el navegador que utilices, el sistema operativo que utilices, distintas versiones de SSOO, etc.
Tampoco tiene que ver con las cookies.
Si necesitáis más información puedo hacer capturas o algún video y enviároslos.
