### ISSUE TITLE
Gundisalvo vuelve a las andadas.

### ISSUE THREAD

**Issue by ManjiChiba** [AyuntamientoMadrid/consul#493]
Se ve que este personajillo clonado y re-clonado no se da por vencido y me toma (y toma a los administradores) por estúpidos.
Ya vuelve a las andadas, pero además, es que no es muy listo ni disimulando, vuelve utilizando las mismas técnicas.
Se ve que no se cansa de que le echéis.
https://decide.madrid.es/users/27858?filter=comments&page=1
¿Cuántos clones más se habrá creado en su momento?
Los sabremos en próximos capítulos.

**Comment by decabeza** [comment]
@ManjiChiba los issues de github se utilizan exclusivamente para funcionalidades técnicas. 

Si hay algún problema con el contenido publicado por otro usuario utiliza el botón de `Denunciar como inapropiado` en el debate/propuesta/comentario que corresponda. 

Gracias.

**Comment by ManjiChiba** [comment]
Ok.
Aunque estaría bien que se os pudiera explicar en un text box el motivo (más que nada por vosotros).
En unas cuantas horas borro o cierro este hilo.

**Comment by ManjiChiba** [comment]
¿Hay algún sitio similar a este o algún lugar donde me pueda dirigir entonces a los administradores para estas sugerencias?.
