### ISSUE TITLE
Problema con las cookies.

### ISSUE THREAD

**Issue by ManjiChiba** [AyuntamientoMadrid/consul#496]
¿Se ha cambiado algo en la programación de las cookies hace unos 7 días?.
El problema que tengo tiene que ver con ellas (quizás no sea el único usuario afectado).
![error](https://cloud.githubusercontent.com/assets/16508522/21540892/ddfbc5e8-cdb2-11e6-9b90-f972421d0417.jpg)
Además, es raro, porque SI se permite replicar un comentario de otro usuario, pero NO permite que puedas crear uno nuevo, de hecho, ni siquiera te lo envía.
El mensaje sale a la creación o modificación (al guardar los cambios) de una propuesta.
Esto no pasa cuando borras las cookies y reinicias el navegador, pero claro... así es imposible hacer nada y si las desactivas.... pues aún peor.

**Comment by ManjiChiba** [comment]
He estado realizando más pruebas y he llegado a alguans conclusiones.
Ahora, por algún motivo que desconozco, se impide poder poner http:// tanto a la hora de enviar un mensaje privado como en la parte "Resumen de la propuesta".
En el primer caso, me está complicando (y mucho) la posibilidad de ir intentando (con paciencia) agrupar propuestas similares en una misma, enviando mensajes privados con enlaces a propuestas más generales para poder agrupar.
Otra cosa que me he dado cuanto que ocurre, es que, mientras antes se podía copiar y pegar desde un documento word y daba igual que este texto estuviera con cualquier tipo de letra, ya que, creo, lo que se hacía al enviar la propuesta (o la modificación), era convertirlo todo automáticamente a un mismo tipo de letra por defecto, ahora, parece que ya no lo hace, y si has hecho un copy/paste desde un documento word, y los tipos de letra (fuentes), son diferentes en el desarrollo de la propuesta... da este extraño error (comprobado con MoviStar que no tiene nada que ver con Firewalls intermedios).
Sin embargo, si en vez de hacer un copy/paste desde un documento word, lo haces desde otra propuesta (entiedo que se usa el mismo tipo de letra), SI funciona y NO da ningún error (al igual que si se re-escribe el mismo texto sin más).
Supongo que este pueda ser el efecto colateral de algún cambio en la programación.
A lo mejor os pueda dar alguna pista de que es lo que se ha cambiado que este afectando a este tema.
Por el momento, puedo seguir agrupando propuestas, evitar que se creen nuevas repetidas redireccionando apoyos, etc, pero con el doble de trabajo y tiempo que antes.
Espero ser de ayuda con las pruebas que he realizado.
Por cierto, Feliz año Nuevo.

**Comment by xuanxu** [comment]
Tema no relacionado con consul
