### ISSUE TITLE
¿Bugs de programación?

### ISSUE THREAD

**Issue by ManjiChiba** [AyuntamientoMadrid/consul#513]
Me he encontrado con algún tipo de bug (¿o talvez algún troll esté lanzando algún tipo de script o algo similar?).
https://decide.madrid.es/proposals/15116-regulacion-de-la-venta-de-material-pirotecnico-a-particulares
La vecina Raquel85 me ha confirmado que ella no ha hecho ningún copia/pega.
Y en esta otra propuesta, parece que también ha pasado lo mismo a otros 2 usuarios.
https://decide.madrid.es/proposals/15122-guardarropas-o-consignas-en-puntos-estrategicos-del-centro
¿Alguien está intentando boicotear la web?.

**Comment by voodoorai2000** [comment]
Gracias por darte cuenta de esto y llamarlo a nuestra atención @ManjiChiba. 
Se introdujo un bug en producción que causó este problema, ya está resuelto, pero los comentarios duplicados siguen ahí. En cuanto tengamos un ratillo los limpiamos ;)

**Comment by ManjiChiba** [comment]
Ok. pues entonces por mi parte, podeis borrar el issue.
Aunque también os comento (no se si será cosa de algún bug o no), que el copy/paste desde un documento word, no funciona bien (creo que tiene que ver con algo de la conversión automática de los tipos de letra, pero no estoy seguro).
Tampoco acepta que aparezca http:// o https:// en los comentarios.

**Comment by voodoorai2000** [comment]
Genial, lo dejo abierto de momento para que no se nos olvide.

Sobre los otros temas que comentas, lo siento, pero no puede reproducirlo. He podido hacer copy paste desde un Word e incluir un link. ¿Puedes volver a probar y pasarme un link del comentario que no te permite hacer esto?

**Comment by ManjiChiba** [comment]
Cuando tenga un rato hago mejor unas capturas de pantalla y las subo.

**Comment by ManjiChiba** [comment]
Cuando hago un copy/paste desde word, los tipos de letra como que se queda igual que en word (antes, hace como hasta unas 2 semanas, esto no ocurría, si no que, era como si en la parte cliente, se transformara todo a un mismo tipo de letra o algo parecido y no daba ningún error).
![error1](https://cloud.githubusercontent.com/assets/16508522/21911499/56562c44-d921-11e6-8695-9a2f0b34a809.jpg)
El error que da es este.
![error2](https://cloud.githubusercontent.com/assets/16508522/21911508/66253548-d921-11e6-8331-7a6face6c269.jpg)
Sin embargo, si en vez de hacer un copy/pastes desde word, lo escribes (se pueden ver como distintos tipos de letra entre lo escrito y lo copy/paste), entonces, funciona sin problema.
![error4](https://cloud.githubusercontent.com/assets/16508522/21911554/94429fc4-d921-11e6-82b9-e179ce1cca82.jpg)
Es decir, si lo dejas así (sólo escrito).
![error5](https://cloud.githubusercontent.com/assets/16508522/21911575/a905d4b2-d921-11e6-80b3-0befaa7253fc.jpg)
Así, funciona (no se porque, es como algo en la validación en la parte cliente en JavaScript, Ruby o lo que utilicéis).
![error6](https://cloud.githubusercontent.com/assets/16508522/21911608/c6697068-d921-11e6-8ed6-ba7af48d9247.jpg)
Otra cosa muy rara que ocurre, es que ahora, no se porque, ni en las notificaciones, ni en los mensajes privados, te acepta un link (la parte de htttp:// o https://), da el mismo error anterior:
ej de cuando va a fallar.
![errornotific1](https://cloud.githubusercontent.com/assets/16508522/21911646/f0d0a52e-d921-11e6-92df-9dc8fa9b0fe4.jpg)
Ejemplo de cuando esta bien y funciona.
![errornotific2](https://cloud.githubusercontent.com/assets/16508522/21911656/fd077516-d921-11e6-8718-f903b039109f.jpg)
esto complica enormemente el poder ir agrupando las propuestas, puesto que la mayoría de las personas tiene escasos conocimientos y si no les suministras un link directos, no saben como llegar hasta la propuesta o hacer un copy/pasta a la barra de direcciones o copiarla como parte de un nuevo mensaje privado o una nueva notificación.
También ocurre con los mensajes privados.
![errornotific1](https://cloud.githubusercontent.com/assets/16508522/21911699/32332424-d922-11e6-8069-e229e1b1ced6.jpg)
(falla)
![errornotific2](https://cloud.githubusercontent.com/assets/16508522/21911701/39748f16-d922-11e6-9e02-f38f09a204a6.jpg)
(funciona)
Espero que esto os pueda dar alguna pista de que es lo que pueda estar ocurriendo ahora (es una de las cosas más raras que he visto nunca en mi vida).
Como digo, esto empezó a ocurrir como hará unas 2 semanas creo que más exactamente desde el viernes 30 (aprox).
Lo comento por si os pueda dar alguna pista, sobre algún cambio que se realizará sobre esas fechas y puedan ir por ahí los problemas.

**Comment by ManjiChiba** [comment]
He grabado un vídeo de las cosas extrañas que ocurren desde hace un par de semanas, pero pesa 110 Mb y no permite subirlo.
Yo creo que es algo relacionado con JavaScript o con los códigos de salto de línea, o con los códigos de párrafo <p>.
Si me dejan una dirección e-mail les envío el vídeo.

**Comment by ManjiChiba** [comment]
Cosas más alucinantes pasan ahora en la edición.
En el párrafo que pone "En ciertos eventos...", y pongo el párrafo separado (justo en esa parte, NO en ninguna otra) con un retorno de carro, SI funciona y se graba,
Sin embargo, si lo junto todo (como está en la propuesta original), da el error (no entiendo nada).
Si hago un copy/paste (sólo falla con este párrafo, no cuando están todos los demás sin este).
![15173error1](https://cloud.githubusercontent.com/assets/16508522/21966140/309d2eb8-db6e-11e6-8457-4a16196ecdcd.jpg)
No había visto nunca nada parecido antes.

**Comment by ManjiChiba** [comment]
mmmm, extraño, parece que ahora vuelve a funcionar bien (por el momento, llevo varias propuestas sin problemas, veremos a ver el resto).
¿habéis hecho algún cambio o modificación?.

**Comment by ManjiChiba** [comment]
Otra vez vuelvo a tener problemas (estoy casi seguro que es algo relacionado con JavaScript).
Algunas veces si me deja poner el https:// en otras no (no he conseguido averiguar que patron sigue).
http:// tampoco me deja ponerlo, pero sin embargo, luego hace la conversión a enlace de internet (que se pueda pulsar y abre pestaña con la nueva página).
![error extrano en propuesta 9625 - 1](https://cloud.githubusercontent.com/assets/16508522/22864406/34616b1a-f151-11e6-93a3-8c16bd78e73f.jpg)
![error extrano en propuesta 9625 - 2](https://cloud.githubusercontent.com/assets/16508522/22864415/40ade272-f151-11e6-982f-4c50932c2582.jpg)

**Comment by ManjiChiba** [comment]
Comprobado, NO es sólo un problema que tenga yo (de mi equipo, ni de mi conexión, ni de mi ISP).
Más personas tienen el mismo problema.
https://decide.madrid.es/proposals/15967-eliminar-las-falsas-sanciones-por-consumo-de-alcohol-en-madrid

**Comment by voodoorai2000** [comment]
Gracias @ManjiChiba sí lo hemos podido reproducir. Gracias por avisarnos, en cuanto tengamos un ratillo lo arreglamos ;)

**Comment by voodoorai2000** [comment]
Sí y gracias por el feedback sobre las votaciones :)

**Comment by ManjiChiba** [comment]
Cada día va peor y aparecen errores nuevos e incomprensibles (por lo menos para mi).
![17015a](https://cloud.githubusercontent.com/assets/16508522/23581758/28ec5b76-011b-11e7-98b6-8b1cadfea552.jpg)
La línea marcada en negrita da error por algún motivo que desconozco.
Se quita y.... sin problemas.
En esta ocasión, aunque se re-escriba entera, sigue dando error.
También vuelve a dar error el poner https:// en el cuerpo de la propuesta y en los Mensajes Privados.
Estoy casi seguro que tendrá algo que ver con JS.

**Comment by voodoorai2000** [comment]
Hola @ManjiChiba 

Creemos que este problema se ha resuelto esta mañana.
Era un tema del cortafuegos, que interpretaba incorrectamente los enlaces en formularios y paraba la petición. 

Hemos hecho unas pruebas internas y parece que todo vuelve a funcionar correctamente.

**Comment by ManjiChiba** [comment]
El fin de semana, cuando cree alguna nueva propuesta y solicite alguna fusión ya comento si me sigue dando problemas.
Tb, cuando tenga algo de tiempo, os comento alguna cosilla (poco importante) que se puede mejorar en lo del sistema de votación.

**Comment by ManjiChiba** [comment]
Ya he comprobado este fin de semana que el problema que había con el https:// está solucionado (al final no era cosa de JS como pensaba), pero los errores que siguen igual son los relativos al copy/paste y los distintos tipos de letras (arriba os envíe capturas de varios problemas).
Lo que si, ahora que habéis mencionado lo del Firewall, es que este tipo de problemas empezaron a pasar al mismo tiempo que el del https:// , es decir, y si no me equivoco, coincidiendo con la instalación o alguna modificación en el Firewall (lo digo, por intentar acotar, donde pueda estar el problema).
