### ISSUE TITLE
¿Recomendac de leer el Listado de Propuestas NO Repetidas ANTES de hacer prop?

### ISSUE THREAD

**Issue by ManjiChiba** [AyuntamientoMadrid/consul#550]
https://decide.madrid.es/debates/4985

Sí, ya se, que esto es un tema de administración, pero... ¿cómo me puedo poner en contacto con los administradores?.
Creo que sería una buena idea para evitar que se sigan repitiendo propuestas ya existentes.
Desde que se han empezado a recibir las invitaciones para las próximas y cercanas votaciones de las 2 propuestas, la cosa se ha desmadrado.
Muchos usuarios nuevos, y montón de propuestas que se repiten.
En fin, espero que la idea, pueda ser de ayuda.

**Comment by voodoorai2000** [comment]
Hola @ManjiChiba, 

Muchas gracias por tu interés en mejorar la web.

Sí, es un problema del que somos conscientes y que queremos resolver.

Ahora mismo estamos todos a tope con la votación de 13 al 19 de Febrero, incluidos los administradores, en cuanto pase esta votación, revisamos este tema y los otros que nos has puesto por aquí ;)

**Comment by ManjiChiba** [comment]
Sí, entiendo, es fundamental que esta primera votación/piloto se haga bien a la 1ª (algunos ya están deseando que la cosa vaya mal para poder mal-meter).
Es una empresa muy grande y tiene que salir bien (se ha empezado muy bien, enviando con tiempo suficiente las cartas, todo un acierto).
A ver si es todo un éxito, puesto que estoy muy ilusionado y ansioso.
Van a ser las 1ªs votaciones en este país (o provincia) que yo considero Realmente Democráticas.
De aquí a rebasar a Suiza... 2 días y luego... las estrellas (que soñar es gratis).
