### ISSUE TITLE
Hashtag al compartir en redes sociales

### ISSUE THREAD

**Issue by voodoorai2000** [AyuntamientoMadrid/consul#65]
Añadir #decidemadrid al compartir en Twitter.

**Comment by bertocq** [comment]
¿En cualquier botón de compartir en Twitter? Por lo que he visto existen:

1- En la página de detalle de un debate
2- En la página de detalle de una proposal
3- Al votar una propuesta en el listado aparecen los botones de share
4- Al votar una propuesta destacada aparecen los botones de share 
5- Varios ficheros más que no consigo encontrar donde se usan (spending_proposals, survey_answers) y los específicos del debate de Plaza España.

Supongo que serían los 2 primeros, pues en los 2 segundos se añade al final ya un "vía @abriendomadrid" tirando de **setting['twitter_handle']**. Esto último me hace pensar que quizás ese tag "#decidemadrid" debería ir por ejemplo en un **Setting["twitter_hastag"] = "decidemadrid"**

Dando con las apariciones de la función **social_share_button_tag** se podría solucionar rápido una vez decidido que hacer.

**Comment by bertocq** [comment]
¿En cualquier botón de compartir en Twitter? Por lo que he visto existen:

1- En la página de detalle de un debate
2- En la página de detalle de una proposal
3- Al votar una propuesta en el listado aparecen los botones de share
4- Al votar una propuesta destacada aparecen los botones de share 
5- Varios ficheros más que no consigo encontrar donde se usan (spending_proposals, survey_answers) y los específicos del debate de Plaza España.

Supongo que serían los 2 primeros, pues en los 2 segundos se añade al final ya un "vía @abriendomadrid" tirando de setting['twitter_handle']. Esto último me hace pensar que quizás ese tag "#decidemadrid" debería ir por ejemplo en un Setting["twitter_hastag"] = "decidemadrid"

Dando con las apariciones de la función social_share_button_tag se podría solucionar rápido una vez decidido que hacer.

**Comment by decabeza** [comment]
Hola @bertocq, se podría poner en todos los botones de compartir en twitter. 

Como el mensaje se puede editar antes de publicarlo no habría problema en que apareciesen las dos cosas `"#decidemadrid Título de lo que se comparte vía @abriendomadrid"` :wink:

**Comment by bertocq** [comment]
Ok @decabeza, entiendo que en en los dos específicos del debate de Plaza España no haría falta pues ya se incluye "Remodelación Plaza de España #decideplazaespaña".

¿Tiene más sentido poner el hashtag delante del título que al final? me resulta raro ahí. Ahora mismo se usa el formato Titulo + Link + via @abriendomadrid (sólo en algunos):

> Pasos de cebra y rejillas anti-deslizantes por la seguridad de bicis y motos https://decide.madrid.es/proposals/9982-pasos-de-cebra-y-rejillas-anti-deslizantes-por-la-seguridad-de-bicis-y-motos vía @abriendomadrid

**Comment by bertocq** [comment]
Bueno para algo tan sencillo quizás no hace falta más debate, he puesto el hashtag tras el título:

Titulo + Hashtag + Link + via (opcional)

**Comment by voodoorai2000** [comment]
:clap:

Closed via #https://github.com/consul/consul/pull/1037
