### ISSUE TITLE
¿Se publicarán estadísticas sobre las recientes Votaciones Ciudadanas?

### ISSUE THREAD

**Issue by ManjiChiba** [AyuntamientoMadrid/consul#669]
Bueno, en primer lugar, me gustaría felicitaros por el Titánico esfuerzo que habéis hecho en la parte de Desarrollo de Software.
Crear y desarrollar una aplicación tan grande, enorme, y con soporte para tantísimos usuarios es algo épico, de hecho, desconozco si hay algo similar implementado ya en algún otro lugar (Suiza incluida, pues me consta el sistema tradicional de urnas, pero no se si también se puede hacer electrónicamente y si pueden hacer propuestas ciudadanas).
Lo que el Empire State Building es a la Ingeniería de Arquitectura, Decide Madrid lo es a la Ingeniería de Desarrollo de Software.
Creo que todo ha funcionado muy bien (9/10, pues siempre hay cosas que se pueden pulir).
De hecho, para ser el primer intento/aproximación/Piloto, ha salido sorprendéntemente bien (yo me esperaba más fallos, pues es normal en la primera aproximación).
¿Vais a publicar estadísticas?.
A mi, personalmente, me parece que serían bastante interesantes:
- Cantidad global de participación.
- Cantidad de participación por Distritos.
- Distribución por edades.
- Distribución del sistema utilizado (votación electrónica, votación por correo ordinario, votación en urna).
- Cantidad de voluntarios de cada Distrito (es decir, NO en cada Distrito, sino, la cantidad de voluntarios que se han presentado de CADA distrito)

Y por si puede ser de utilidad esta sugerencia para futuras votaciones...
https://decide.madrid.es/proposals/16628-reutilizacion-y-reciclaje-de-las-papeletas-de-consultas-de-propuestas-ciudadanas
Y por si alguno habéis hecho horas extras fuera de la oficina....
https://decide.madrid.es/proposals/16477-voluntariado-para-referendums-ciudadanos-por-multas-sanciones

**Comment by xuanxu** [comment]
Hola @ManjiChiba, muchas gracias!
En cuanto a tu pregunta, la respuesta es sí: Junto con los resultados, vamos a publicar estadísticas de participación totales y desglosadas por canal (web, urna, correo) y por edad/género/distrito. :tada:

**Comment by ManjiChiba** [comment]
Ok.
(¿Currando un Domingo?, tómate un kit-kat hombre 😊)
