### ISSUE TITLE
Botón de visita.

### ISSUE THREAD

**Issue by ManjiChiba** [AyuntamientoMadrid/consul#670]
Para cuando tengáis tiempo y estéis menos liados.
https://decide.madrid.es/proposals/14260-boton-de-visita
Creo que sería útil y podría motivar al borrado de propuestas.

**Comment by decabeza** [comment]
Estamos trabajando en la nueva funcionalidad "Panel de control de propuestas" https://github.com/consul/consul/issues/2981 que permitirá a los autores tener una visión de como está funcionando su propuesta a través de un gráfico. :)
