### ISSUE TITLE
Aumentar el Row en los textbox.

### ISSUE THREAD

**Issue by ManjiChiba** [AyuntamientoMadrid/consul#682]
Aumentar al máximo el ancho que permita (¿Row?) de los campos de texto como este.
Es un verdadero incordio, tener que estar continuamente redimensionando al máximo los textbox para que te permita ver todo el texto a la vez, o tener que estar haciendo scrolling en la barra de la derecha.
Es mejor como esta aquí, que de entrada, ya te da el máximo (supongo) de rows para poder escribir.
Esto pasa en los textbox de los comentarios y en el de los mensajes privados.
Se que es una chorrada, pero para el que tiene que escribir en ellos, es una tortura.

**Comment by bertocq** [comment]
Closing as duplicated of https://github.com/AyuntamientoMadrid/consul/issues/1089 and that one has "better" description
