### ISSUE TITLE
Estadísticas Demográficas

### ISSUE THREAD

**Issue by voodoorai2000** [AyuntamientoMadrid/consul#812]
### Qué
Preparar la página de estadísticas demográficas para los Presupuestos Participativos de este año.
Debería ser igual que [la del año pasado](https://decide.madrid.es/presupuestos-participativos-estadisticas)

### Cómo
El código actual está [aquí](https://github.com/AyuntamientoMadrid/consul/blob/master/app/controllers/spending_proposals_controller.rb#L71)

Se hizo muy rápido y un poco guarrete... habría que crear una clase dentro del namespace Budget con la lógica que ahora está en el controlador.

### Nota
Esta funcionalidad estaría genial llevarla a Consul pero no es prioritario y puede tener su intríngulis... Seguramente es mejor dejarlo cerrado en Madrid y ver cómo/qué partes podemos llevar a Consul

**Comment by bertocq** [comment]
@voodoorai2000 tras lo hablado hoy. Entiendo que en la página de estadísticas ya no se usarán las Geozones, pero se podrían sustituir en el bloque "Participación por distritos" por los Headings, de forma que aunque no saldría el mapa... si se podría conservar la tabla (me parece bastante informativa y detallada) quitando obviamente las columnas `% Censo Distrito` pues hemos hablado que los Heading pueden ser algo intangible como "Salud" o "Calle 30". Right? :)

**Comment by javierm** [comment]
Closed by #839 and #1951.
