### ISSUE TITLE
Traducciones

### ISSUE THREAD

**Issue by voodoorai2000** [AyuntamientoMadrid/consul#815]
### Qué

Crear una cuenta en un servicio de traducciones

### Cuál

Tenemos tres opciones:
[Transifex](https://www.transifex.com/)
[Crowdin](https://crowdin.com/)
[Translator.io](https://translation.io/)

La interfaz de Crowdin parece más intuitiva que la de Transifex.
Translator.io [junta todas las traducciones](https://translation.io/blog/dealing-with-yaml-files-and-their-directory-structure) en un único archivo.
La sincronización de traducciones parece [más pulida](https://support.crowdin.com/cli-tool/) en Crowdin.

La mejor opción parece ser Crowdin

### Cómo 

- Hacer una comprobación final de que la sincronización funciona bien.
- Pedirle a Virgile que nos transfiera la cuenta de Consul en Crowdin que ha creado
- Subir todas las traducciones que tengamos

### Por qué

Tenemos reunión en Holanda el día 20(la semana que viene). Para entonces debería estar Budgets completamente traducido en Consul y Madrid.

Francia también tiene muchas ganas de montar las traducciones bien y ya han enviado una PR

### Nota

También hemos de decidir dónde guardamos las traducciones en Consul.
En mi opinión, deberíamos empezar metiendo las PRs de los colaboradores de Holanda y Francia y luego refactorizar o extraer a otro repo si/cuando crezca el número de idiomas.

También creo que habría que cambiar la estructura de archivos de /config/locales/* a config/locales/en/, config/locales/fr/, para que quede más organizado

**Comment by bertocq** [comment]
Todavía falta que arreglen un bug en Crowdin para poder empezar a usarlos al 100%...

**Comment by bertocq** [comment]
Estamos pendientes de que el miércoles arreglen en crowdin su bug interno con `zero:` de rails

**Comment by voodoorai2000** [comment]
Closed via consul/consul#1718 🎉
