### ISSUE TITLE
Optimizar la generación de csvs de datos

### ISSUE THREAD

**Issue by xuanxu** [AyuntamientoMadrid/consul#819]
Ahora mismo se están generando los csvs para el portal de datos abiertos en [todas las máquinas de producción](https://github.com/AyuntamientoMadrid/consul/pull/818).

Hay que optimizar el proceso una vez que tengamos el directorio compartido apropiado funcionando para que se haga una sola vez y se copie a las demás.

**Comment by bertocq** [comment]
Relacionada con https://github.com/AyuntamientoMadrid/consul/issues/814

**Comment by bertocq** [comment]
Closed via https://github.com/AyuntamientoMadrid/consul/pull/843
