### ISSUE TITLE
Create a rake task to update valid users

### ISSUE THREAD

**Issue by bertocq** [AyuntamientoMadrid/consul#834]
## What
An registered and validated user could move to another city and leave the census... that would make him as non valid user. We need to periodically check for those scenarios and disable the users

## How
A rake task included in the cron jobs. 
- The rake should be generic enough to be integrated in consul/consul to be reused. 
- Obviously the rake task would be calling a object/serviceobject class that would know the specifics of the service/integration with each city census.
- If user is no longer in census, remove the verified status, and notify them via email. If he's back in, verify him again, and should as well be notified.
- The "verification removal email" alert should explain the reason behind the removal of his user account verification, and a way to resolve it in case of its a mistake (like send an email to `<here>`)

## Notice
The comments of this issue where used to gather more detailed specs and complete the description, don't get bothered or distracted by them... both `What` and `How` are completed and updated 👍

**Comment by bertocq** [comment]
@voodoorai2000 questions. What should happen to a user that got out of the census? And I'm both asking for madrid and consul

**A-** Deactivate it (he cannot longer login, so no auth interactions at all)?

**B-** Let him still modify his proposals/budgets, but no new debates/proposals/votes/polls?

I assume A for consul as default, but maybe on Madrid we don't want to be so much restrictive?

Also I would assume it would be needed to:

1. Send an email should be sent to alert of the deactivation of the user account, the reason, and a way to resolve it in case of its a mistake (like send an email <here>). **New issue for this should be created later on.**

2. In order to enable a user that got disabled by a mistake in the census. Going up to census workers/systems would be the only way to go... and then manual action in admin panel to "re-activate user" that would ask for that user being included in the census. **New issue for this should be created later on.**

3. Somehow show that user as "no longer active" in the user interface, for information purposes to other users that may expect him to answer in debates or such things. **New issue for this should be created later on.**

**Comment by xuanxu** [comment]
about **A**: No need to deactivate user, only remove the verified status. User should be able to use the web and partcipate as a regular not verified user.

**Comment by voodoorai2000** [comment]
Awesome!

+1 @xuanxu's comment
+1 to 1) and 2)

Regarding 3) there is no real way of knowing if a user is verified from the public interface.
I don't think there is a need to do things here

**Comment by voodoorai2000** [comment]
Regarding 2) we now have a section in Management, where non verified users can be verified.

**Comment by voodoorai2000** [comment]
Closed in favor of consul/consul#1887
