### ISSUE TITLE
Traducción urls

### ISSUE THREAD

**Issue by decabeza** [AyuntamientoMadrid/consul#857]
Información
===

Ahora mismo hay una mezcla de urls en castellano y en inglés. Al tratarse de una web del Ayuntamiento de Madrid, todas las urls deberían estar en castellano.

También se puede utilizar _i18n_ en las urls para que estén en el _locale_ seleccionado.

Qué necesitamos
===

Traducir todas las urls al castellano (manteniendo o no las de inglés y resto de idiomas disponibles), por ejemplo:

- `/proposals => /propuestas`
- `/account => /mi-cuenta`
- `/users/N => /mi-actividad`
- (...)

**Comment by iagirre** [comment]
I'll do this one.

**Comment by iagirre** [comment]
He empezado a traducir las URL, pero me he topado con que hay algunas que están repetidas tanto en los archivos refactorizados como en el archivo custom.rb (por ejemplo las de budget, en el archivo [budget.rb](https://github.com/AyuntamientoMadrid/consul/blob/master/config/routes/budget.rb#L1) y en el [custom.rb](https://github.com/AyuntamientoMadrid/consul/blob/master/config/routes/custom.rb#L36))
¿Cuáles son las que hay que traducir, las de custom o el resto?

**Comment by voodoorai2000** [comment]
En efecto, hay una pequeña redundancia que deberíamos arreglar en algún momento. 
Sería bueno tener las traducciones listas en ambos archivos ahora que nos ponemos con ello 😌👏💪
