### ISSUE TITLE
Forma de unir varias propuestas en una, unificando votos.

### ISSUE THREAD

**Issue by andreujuanc** [AyuntamientoMadrid/consul#9]
Buenas, soy programador y usuario del site. Mientras navegaba me he dado cuenta que hay muchos topics abiertos sobre el mismo tema y no encontré si existía forma de unirlos. Luego al enterarme de que el proyecto está en GH se me ocurrió hacer un fork y programarlo, pero antes quisiera preguntar si esta en proceso, si existe la incidencia, o si alguna otra persona tuvo la misma idea.

Debería ser algo así: 
- Usuarios sugieren duplicidad del tema al creador.
- Creador mira el enlace y acepta que su tema está duplicado.
- Se unifican los temas en uno solo. Sumando los votos/apoyos que no estén en el primero.
- Buscar una forma de llevarse también los comentarios.

Gracias, un saludo.

**Comment by xuanxu** [comment]
Gracias por la propuesta @andreujuanc 
Efectivamente la repetición de propuestas es un tema que nos preocupa y se está trabajando en un par de issues en marcha para solucionarlo, están en el [repositorio padre](https://github.com/consul/consul), son estos dos: [588](https://github.com/consul/consul/issues/588) y [599](https://github.com/consul/consul/issues/599).
Justo hacen referencia a casi todo lo que propones, excepto sumar votos/comentarios porque para eso habría que pedir permiso a todas aquellas personas que han apoyado una propuesta, no podemos trasladar los apoyos automaticamente aunque las propuestas sean muy similares.
Cierro este issue para evitar duplicidades.
