### ISSUE TITLE
Notificaciones

### ISSUE THREAD

**Issue by decabeza** [AyuntamientoMadrid/consul#954]
What
===
- Fix in-app notifications

How
===
- Making sure when someone responds to your comment or creates a root comment, the in-app notification does not through an exception
- Check for the following commentables (debate, proposal, investment, poll and topic, legislation_proposal)

Note
===
Inform our worried users once this is fixed
https://decide.madrid.es/debates/5258-funcionan-los-mensajes-privados

**Comment by decabeza** [comment]
No sé si está relacionado, pero en `/mailers/mailer.rb` tenemos una condición diferente que no está en CONSUL: `unless Rails.env.production?` justo para los comentarios y respuestas 🤔

**Comment by ManjiChiba** [comment]
![nuevoerror](https://user-images.githubusercontent.com/16508522/32984531-8e846ac4-cca8-11e7-8dec-e5316171f000.jpg)

**Comment by ManjiChiba** [comment]
¿Algunas novedad?.
Me esta causando mucho perjuicio este nuevo fallo.

**Comment by voodoorai2000** [comment]
Querido @ManjiChiba,

Muchas gracias por insistir en este problema, ha ayudado a que podamos subir su prioridad 👍 
Ahora está en el [Roadmap](https://github.com/consul/consul/projects/6) y en breve estará arreglado y en producción, te avisamos :)

Sobre el tema de envío de emails, también tienes razón. Tuvimos un problema de SPAM y capamos el envío de notificaciones por email. Debemos revisar las medidas anti-SPAM y lo reactivamos.

**Comment by ManjiChiba** [comment]
Es normal que nadie más se haya quejado.
La mayoría de los proponentes "lanzan" la propuesta, y luego se olvidan por completo, además, tienen pocas propuestas o muy antigüas (sin visibilidad, ni nuevos comentarios), con lo cual, puede que ni se hayan dado cuenta, pero en mi caso, al manejar tantas... pues ya veis, casi ya 900 comentarios a los que no he podido responder, y me fastidia, porque los ciudadanos pueden pensar (equivocadamente), que paso de ellos o de lo que comenten, y claro, el que sólo tiene 1 o 2 propuestas, puede mirar manualmente cada día, si hay comentarios nuevos o no, pero en mi caso, eso es inviable.
Lo del SPAM... no lo entiendo muy bien, pero... a ver si voy a estar contribuyendo a ello sin saberlo.
Lógicamente, si envío una notificación en una propuesta como esta:
https://decide.madrid.es/proposals/16081-1-hora-de-parking-exenta-de-pago-en-los-hospitales
implica la salida de muchos e-mails en el servidor de correo saliente, pero... vamos, he dado siempre por sentado, que teníais configurado algún tipo de temporizador, para que fueran saliendo cada x segundos y que así no se sature el servidor/es (imagino que estará balanceado) de correo saliente (lo mismo he supuesto demasiado).

**Comment by ManjiChiba** [comment]
Ya puedo acceder a buzón de mensajes y ya no me sale el error 500 (espero que fuera al único que le pasaba, pues no he leido nada de ningún otro ciudadano al que le haya pasado lo mismo).
Que siga sin recibir un mensaje al e-mail cuando una persona contesta en una propuesta (o responde a un comentario) ya no es tán urgente (ahora que ya puedo acceder al buzón).
Lo que si creo que recibo es un e-mail cuando me envían un mensaje privado.
Tengo pendiente probar cuando me envían una notificación.
