### ISSUE TITLE
Recuperar formulario jornadas presupuestos participativos

### ISSUE THREAD

**Issue by bertocq** [AyuntamientoMadrid/consul#993]
Indagar en el git history y recuperar `https://decide.madrid.es/jornada-presupuestos-participativos`  tal cual lo tuvimos en su momento (quizás el history de `config/routes.rb` pueda ser el que más ayude)

**DEADLINE: ASAP**

**Comment by decabeza** [comment]
I found the old commits related with this form:

- Implements backend for temporary budget poll: https://github.com/AyuntamientoMadrid/consul/commit/8c84c1029d8af78168ad6feaee6c05fe91928062

- Adds root link for budget_poll/new: https://github.com/AyuntamientoMadrid/consul/commit/795212150db6756ecc519e32e2952b07065a5371

- Adds info text on budget_poll new form: https://github.com/AyuntamientoMadrid/consul/commit/6d937248bbb6e680b5ceb2abbb80a27b14f2e73c

- Adds help checkbox to form: https://github.com/AyuntamientoMadrid/consul/commit/6c86d4b22a6d0e5f18a7940b00f663419a61cd20

**Comment by bertocq** [comment]
https://decidepre.madrid.es/jornada-presupuestos-participativos

Los mails de los 311 ganadores: 214 
`User.where(id: Budget::Investment.winners.pluck(:author_id).uniq).pluck(:email)`

Los mails de los finalistas: 290
`User.where(id: Budget::Investment.selected.where.not(id: Budget::Investment.winners.pluck(:id)).pluck(:author_id).uniq).pluck(:email)`

Los mails de todos los proponentes 1222
`User.where(id: Budget::Investment.where.not(id: Budget::Investment.selected.pluck(:id)).pluck(:author_id).uniq).pluck(:email)`

**Comment by bertocq** [comment]
quizas haga falta excluir emails repetidos entre los 3 listados (restamos excluyendo solo propuestas) y algun dato mas ... 🤔

**Comment by bertocq** [comment]
Closed via #1009 (deployed to pro already)
